/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package preliquidaciones;

import Alertas.ErrordeProcesos;
import Alertas.ProcesoExitoso;
import Colas_y_Pilas.Cola;
import EstilodelasTablas.EstiloTablaHeader;
import EstilodelasTablas.EstiloTablaRenderer;
import EstilodelasTablas.MyScrollbarUI;
import EstilodelasTablas.MyScrollbarVistas;
import ListasCirculares.NodoCS;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import proyectos.Proyectos;
import proyectos.dao_proyectos;

/**
 *
 * @author Sony
 */
public class preliquidacionesporproyectos extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    Preliquidaciones preliquidacion = new Preliquidaciones();
    Preliquidaciones preliquidacion1 = new Preliquidaciones();
    dao_preliquidaciones dpr = new dao_preliquidaciones();
    /*Para llena çr la lista correspondiente con los nombre s de los  proyectos*/
    dao_proyectos dp = new dao_proyectos();
    Proyectos proyectos = null;
    DefaultListModel modelolista;
    DecimalFormat fr = new DecimalFormat("0.00");

    /*Cola para el calculo de los saldos por capitulos*/
    Cola colacapitulos = new Cola();

    /**
     * Creates new form NewJInternalFrame
     */
    public preliquidacionesporproyectos() {
        initComponents();
        this.tablaPreliquidaciones.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tablaPreliquidaciones.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tablaPreliquidaciones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.getVerticalScrollBar().setUI(new MyScrollbarVistas());
        jScrollPane2.getHorizontalScrollBar().setUI(new MyScrollbarVistas());
        jScrollPane5.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane5.getVerticalScrollBar().setUI(new MyScrollbarVistas());
        jScrollPane5.getHorizontalScrollBar().setUI(new MyScrollbarVistas());
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.id.setVisible(false);
        this.jLabel18.setVisible(false);
        this.idpre.setVisible(false);
        titulo2.setText("Nuevo registro");
        this.id.setText("");
        this.jLabel18.setText("");
        this.importeproyecto.setEditable(false);
        this.importeliquidaciones.setEditable(false);
        model = (DefaultTableModel) tablaPreliquidaciones.getModel();
        modelolista = new DefaultListModel();
        listadoproyectos.setModel(modelolista);
        llenarlista();
        ocultar_columnas();
    }

    void ocultar_columnas() {
        this.tablaPreliquidaciones.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tablaPreliquidaciones.getColumnModel().getColumn(0).setMinWidth(0);
        this.tablaPreliquidaciones.getColumnModel().getColumn(0).setPreferredWidth(0);

        this.tablaPreliquidaciones.getColumnModel().getColumn(9).setMaxWidth(0);
        this.tablaPreliquidaciones.getColumnModel().getColumn(9).setMinWidth(0);
        this.tablaPreliquidaciones.getColumnModel().getColumn(9).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialButtonCircle1 = new principal.MaterialButtonCircle();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        buscar = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        totregistros = new javax.swing.JLabel();
        btnbuscar = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jPanel5 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        listadoproyectos = new javax.swing.JList<>();
        capitulo1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        titulo2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        claseobra = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        capitulo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        precioproyecto = new app.bolivia.swing.JCTextField();
        unidadesproyecto = new app.bolivia.swing.JCTextField();
        jLabel12 = new javax.swing.JLabel();
        importeproyecto = new app.bolivia.swing.JCTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        unidadesliquidaciones = new app.bolivia.swing.JCTextField();
        jLabel16 = new javax.swing.JLabel();
        importeliquidaciones = new app.bolivia.swing.JCTextField();
        jLabel17 = new javax.swing.JLabel();
        idpre = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        diferencia = new app.bolivia.swing.JCTextField();
        jLabel20 = new javax.swing.JLabel();
        btnGuardar = new principal.MaterialButton();
        btnCancelar = new principal.MaterialButton();
        importpre = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        importproy = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        diferenciapre = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPreliquidaciones = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btncerrar = new principal.MaterialButton();

        materialButtonCircle1.setText("materialButtonCircle1");

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        buscar.setBackground(new java.awt.Color(255, 255, 255));
        buscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(26, 187, 156)));
        buscar.setForeground(new java.awt.Color(26, 187, 156));
        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setPlaceholder("BUSCAR PRELIQUIDACIÓN");
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 63, 84));
        jLabel2.setText("Total de Registros");

        totregistros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totregistros.setForeground(new java.awt.Color(42, 63, 84));
        totregistros.setText("0000");

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDonantes/icons8_Search_30px.png"))); // NOI18N
        btnbuscar.setColorHover(new java.awt.Color(229, 226, 229));
        btnbuscar.setColorNormal(new java.awt.Color(255, 255, 255));
        btnbuscar.setColorPressed(new java.awt.Color(248, 246, 246));
        btnbuscar.setColorTextHover(new java.awt.Color(248, 246, 246));
        btnbuscar.setDefaultCapable(false);
        btnbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(26, 187, 156));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel2.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel2MouseDragged(evt);
            }
        });
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(26, 187, 156));

        titulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Proyectos registrados");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel6.setBorder(dropShadowBorder2);

        id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("id");

        listadoproyectos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listadoproyectosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listadoproyectos);

        jScrollPane4.setViewportView(jScrollPane3);

        capitulo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Demoliciones", "Albañileria", "Solados y Alicatados", "Vidriería", "Rehabilitación de Hormigones", "Acabados", "Fontanería", "Electricidad e Iluminación", "Aire Acondicionado", "Cafetería", "Varios", "Alquiler de Herramientas", "Limpieza", "Seguros", "Instalación Sanitaria", "Movimiento de Suelos" }));
        capitulo1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                capitulo1ItemStateChanged(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(26, 187, 156));
        jLabel13.setText("Capitulo:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("<html>Filtrar los datos por capitulos<br><center>según proyecto</center>");

        jLabel18.setText("capitulo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(capitulo1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(capitulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(26, 187, 156));

        titulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo2.setForeground(new java.awt.Color(255, 255, 255));
        titulo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo2.setText("Nuevo registro");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder3 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder3.setShowLeftShadow(true);
        dropShadowBorder3.setShowTopShadow(true);
        jPanel9.setBorder(dropShadowBorder3);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 187, 156));
        jLabel7.setText("Precio:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 187, 156));
        jLabel11.setText("Clas. de Obra:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 187, 156));
        jLabel8.setText("Capitulo:");

        capitulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Demoliciones", "Albañileria", "Solados y Alicatados", "Vidriería", "Rehabilitación de Hormigones", "Acabados", "Fontanería", "Electricidad e Iluminación", "Aire Acondicionado", "Cafetería", "Varios", "Alquiler de Herramientas", "Limpieza", "Seguros", "Instalación Sanitaria", "Movimiento de Suelos" }));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(42, 63, 84));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Proyecto Original");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(42, 63, 84));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Datos Generales del Proyecto");

        precioproyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioproyectoKeyReleased(evt);
            }
        });

        unidadesproyecto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadesproyectoKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(26, 187, 156));
        jLabel12.setText("Unidades:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(42, 63, 84));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Proyecto Liquidaciones");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(26, 187, 156));
        jLabel15.setText("Unidades:");

        unidadesliquidaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                unidadesliquidacionesKeyReleased(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(26, 187, 156));
        jLabel16.setText("Importe:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(26, 187, 156));
        jLabel17.setText("Importe:");

        idpre.setText("idpreliquidaciones");

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(26, 187, 156));
        jLabel19.setText("Diferencia:");

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(42, 63, 84));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Presupuesto menos liquidaciones");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createSequentialGroup()
                                        .addComponent(unidadesproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(idpre, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(importeproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(claseobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(capitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel9Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(unidadesliquidaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(importeliquidaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(diferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26))
                                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(352, 352, 352)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(347, 347, 347))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(claseobra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(capitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(unidadesliquidaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(importeliquidaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(precioproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unidadesproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(importeproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(111, 111, 111)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(diferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idpre)
                                .addContainerGap(66, Short.MAX_VALUE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)
                                .addGap(71, 71, 71))))))
        );

        btnGuardar.setBackground(new java.awt.Color(26, 187, 156));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setToolTipText("");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(243, 156, 17));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(739, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(187, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        importpre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        importpre.setForeground(new java.awt.Color(26, 187, 156));
        importpre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importpre.setText("00.00");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(42, 63, 84));
        jLabel22.setText("Importe Preliquidación:");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(42, 63, 84));
        jLabel23.setText("Importe Proyecto:");

        importproy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        importproy.setForeground(new java.awt.Color(26, 187, 156));
        importproy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importproy.setText("00.00");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(42, 63, 84));
        jLabel24.setText("Diferencia:");

        diferenciapre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        diferenciapre.setForeground(new java.awt.Color(26, 187, 156));
        diferenciapre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diferenciapre.setText("00.00");

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(42, 63, 84));
        jLabel25.setText("Total Capitulo");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tablaPreliquidaciones.setBackground(new java.awt.Color(255, 255, 255));
        tablaPreliquidaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaPreliquidaciones.setForeground(new java.awt.Color(255, 255, 255));
        tablaPreliquidaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDPRELIQUIDACIÓN", "CLASE DE OBRA", "CAPITULO", "PRECIO (PROYECTO)", "UNIDADES (PROYECTO", "IMPORTE (PROYECTO", "UNIDADES (LIQUIDACIONES)", "IMPORTE (LIQUIDACIONES)", "DIFERENCIA", "IDPROYECTO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPreliquidaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaPreliquidaciones.setDoubleBuffered(true);
        tablaPreliquidaciones.setRowHeight(20);
        tablaPreliquidaciones.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaPreliquidaciones.getTableHeader().setReorderingAllowed(false);
        tablaPreliquidaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPreliquidacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPreliquidaciones);
        if (tablaPreliquidaciones.getColumnModel().getColumnCount() > 0) {
            tablaPreliquidaciones.getColumnModel().getColumn(0).setMinWidth(70);
            tablaPreliquidaciones.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1562, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(jPanel8);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importproy, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(importpre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(diferenciapre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totregistros))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(importpre)
                            .addComponent(jLabel22)
                            .addComponent(importproy)
                            .addComponent(jLabel23)
                            .addComponent(diferenciapre)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totregistros))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel7);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 63, 84));
        jLabel1.setText("Preliquidaciones");

        btncerrar.setBackground(new java.awt.Color(42, 63, 84));
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("X");
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(551, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased

    }//GEN-LAST:event_buscarKeyReleased

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String buscar = this.buscar.getText();
        NodoCS dato = dpr.lcsp.buscar(buscar);
        if (dato != null) {
            JOptionPane.showMessageDialog(null, "\t\tDATOS DE LA PRELIQUIDACIÓN\n\n"
                    + "Cla. Obra: " + ((Preliquidaciones) dato.getDato()).getClasedeobra()
                    + "\nCapitulo: " + ((Preliquidaciones) dato.getDato()).getCapitulo()
                    + "\n\nDATOS DEL PRESUPUESTO\n"
                    + "Precio: " + ((Preliquidaciones) dato.getDato()).getPrecioproyecto()
                    + "\nUnidades: " + ((Preliquidaciones) dato.getDato()).getUnidadesproyecto()
                    + "\nImporte: " + ((Preliquidaciones) dato.getDato()).getImporteproyecto()
                    + "\n\nDATOS DE LA LIQUIDACIÓN\n"
                    + "Unidades: " + ((Preliquidaciones) dato.getDato()).getUnidadespreliquidaciones()
                    + "\nImporte: " + ((Preliquidaciones) dato.getDato()).getImportepreliquidaciones()
                    + "\n\nDIFERENCIA PRESUPUESTO Y PRELIQUIDACIÓN\n"
                    + "Diferencia: " + ((Preliquidaciones) dato.getDato()).getDiferencia(),
                    "Busqueda Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.buscar.setText("");
        } else {
            this.buscar.setText("");
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("ERROR DE BÚSQUEDA");
            er.msj.setText("EL REGSITRO NO EXISTE");
            er.msj1.setText("");
            er.setVisible(true);
            this.buscar.setText("");
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseDragged

    }//GEN-LAST:event_panel2MouseDragged

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed

    }//GEN-LAST:event_panel2MousePressed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if (proyectos != null) {
            if (!this.claseobra.getText().isEmpty() && this.capitulo.getSelectedIndex() != 0 && !this.precioproyecto.getText().isEmpty()
                    && !this.unidadesproyecto.getText().isEmpty() && !this.importeproyecto.getText().isEmpty() && !this.unidadesliquidaciones.getText().isEmpty()
                    && !this.importeliquidaciones.getText().isEmpty()) {
                String claseobra = this.claseobra.getText();
                String capitulo = this.capitulo.getSelectedItem().toString();
                double precioproyecto = Double.parseDouble(this.precioproyecto.getText());
                double unidadesproyecto = Double.parseDouble(this.unidadesproyecto.getText());
                double importeproyectos = Double.parseDouble(this.importeproyecto.getText());
                double unidadespreliquidacion = Double.parseDouble(this.unidadesliquidaciones.getText());
                double importepreliquidacion = Double.parseDouble(this.importeliquidaciones.getText());

                preliquidacion.setClasedeobra(claseobra);
                preliquidacion.setCapitulo(capitulo);
                preliquidacion.setPrecioproyecto(precioproyecto);
                preliquidacion.setUnidadesproyecto(unidadesproyecto);
                preliquidacion.setImporteproyecto(importeproyectos);
                preliquidacion.setUnidadespreliquidaciones(unidadespreliquidacion);
                preliquidacion.setImportepreliquidaciones(importepreliquidacion);
                preliquidacion.setIdproyecto(Integer.parseInt(this.id.getText()));

                if (precioproyecto > 0 && unidadesproyecto > 0 && importeproyectos > 0 && unidadespreliquidacion > 0 && importepreliquidacion > 0) {
                    double diferencia = importepreliquidacion - importeproyectos;
                    preliquidacion.setDiferencia(diferencia);
                    preliquidacion1 = buscarclaseobra(claseobra);
                    if (this.btnGuardar.getText().equals("GUARDAR")) {
                        /*OPCION PARA GUARDAR*/
                        if (preliquidacion1 == null) {
                            dpr.insertar(preliquidacion);
                            ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                        er.titulo.setText("REGSITRO GUARDADO");
                        er.msj.setText("REGSITRO INGRESADO");
                        er.msj1.setText("SATISFACTORIAMENTE");
                        er.setVisible(true);
                            titulo2.setText("Nuevo registro");
                            btnGuardar.setBackground(new Color(26, 187, 156));
                            btnGuardar.setText("GUARDAR");
                            llenarTabla(this.id.getText(), this.jLabel18.getText());
                            mostrarimportes(jLabel18.getText());/*actualizara los datos de los saldos */
                            limpiar();
                        } else {
                             ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                        er.titulo.setText("ERROR");
                        er.msj.setText("ESTE TIPO DE OBRA YA HA SIDO");
                        er.msj1.setText("REGISTRADA");
                        er.setVisible(true);
                        }
                    } else if (this.btnGuardar.getText().equals("ACTUALIZAR")) {
                        /*OPCION PARA MODIFICAR*/
                        preliquidacion.setIdpreliquidacion(Integer.parseInt(idpre.getText()));
                        dpr.editar(preliquidacion);
                        ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                    er.titulo.setText("REGSITRO MODIFICADO");
                    er.msj.setText("REGSITRO ACTUALIZADO");
                    er.msj1.setText("SATISFACTORIAMENTE");
                    er.setVisible(true);
                        titulo2.setText("Nuevo registro");
                        btnGuardar.setBackground(new Color(26, 187, 156));
                        btnGuardar.setText("GUARDAR");
                        llenarTabla(this.id.getText(), jLabel18.getText());
                        mostrarimportes(jLabel18.getText());/*actualizara los datos de los saldos */
                        limpiar();
                    }
                } else {
                    ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                er.titulo.setText("ERROR");
                er.msj.setText("INGRESE LOS MONTOS VALIDOS PARA");
                er.msj1.setText("EL PROYECTO");
                er.setVisible(true);
                }
            } else {
               ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("CAMPOS VACÍOS");
            er.msj.setText("POR FAVOR LLENE LOS CAMPOS");
            er.msj1.setText("SOLICITADOS");
            er.setVisible(true);
            }
        } else {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("ERROR");
            er.msj.setText("POR FAVOR SELECCIONE UN");
            er.msj1.setText("PROYECTO");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed

        limpiar();
        titulo2.setText("Nuevo registro");
        btnGuardar.setBackground(new Color(26, 187, 156));
        btnGuardar.setText("GUARDAR");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void listadoproyectosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listadoproyectosValueChanged
        // TODO add your handling code here:
        proyectos = new Proyectos();
        String dato = listadoproyectos.getSelectedValue();
        proyectos = buscaridproyecto(dato);
        String idproyecto = "";
        String capitulo = "";
        if (proyectos != null && this.capitulo1.getSelectedIndex() != 0) {
            limpiar();
            idproyecto = String.valueOf(proyectos.getIdproyecto());
            capitulo = this.capitulo1.getSelectedItem().toString();
            model = (DefaultTableModel) tablaPreliquidaciones.getModel();
            this.id.setText(idproyecto);
            this.jLabel18.setText(capitulo);
            titulo2.setText("Nuevo registro");
            btnGuardar.setBackground(new Color(26, 187, 156));
            btnGuardar.setText("GUARDAR");
            llenarTabla(idproyecto, capitulo);
            mostrarimportes(capitulo);
        } else {
            this.totregistros.setText("0");
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("PROYECTO NO ENCONTRADO");
            er.msj.setText("EL PROYECTO NO EXISTE O NO SE HA");
            er.msj1.setText("SELECCIONADO UN CAPITULO");
            er.setVisible(true);
        }
    }//GEN-LAST:event_listadoproyectosValueChanged

    private void unidadesproyectoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadesproyectoKeyReleased
        // TODO add your handling code here:
        if (!this.unidadesproyecto.getText().isEmpty() && !this.precioproyecto.getText().isEmpty()) {
            double precio = Double.parseDouble(this.precioproyecto.getText());
            double unidades = Double.parseDouble(this.unidadesproyecto.getText());
            double importe = precio * unidades;
            this.importeproyecto.setText(String.valueOf(fr.format(importe)));
        } else {
            this.importeproyecto.setText("");
        }
        if (!this.importeliquidaciones.getText().isEmpty() && !this.importeproyecto.getText().isEmpty()) {
            double dato = Double.parseDouble(this.importeliquidaciones.getText()) - Double.parseDouble(this.importeproyecto.getText());
            this.diferencia.setText(String.valueOf(fr.format(dato)));
        } else {
            this.diferencia.setText("");
        }
    }//GEN-LAST:event_unidadesproyectoKeyReleased

    private void unidadesliquidacionesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_unidadesliquidacionesKeyReleased
        // TODO add your handling code here:
        if (!this.unidadesliquidaciones.getText().isEmpty() && !this.precioproyecto.getText().isEmpty()) {
            double precio = Double.parseDouble(this.precioproyecto.getText());
            double unidades = Double.parseDouble(this.unidadesliquidaciones.getText());
            double importe = precio * unidades;
            this.importeliquidaciones.setText(String.valueOf(fr.format(importe)));
        } else {
            this.importeliquidaciones.setText("");
        }

        if (!this.importeliquidaciones.getText().isEmpty() && !this.importeproyecto.getText().isEmpty()) {
            double dato = Double.parseDouble(this.importeliquidaciones.getText()) - Double.parseDouble(this.importeproyecto.getText());
            this.diferencia.setText(String.valueOf(fr.format(dato)));
        } else {
            this.diferencia.setText("");
        }
    }//GEN-LAST:event_unidadesliquidacionesKeyReleased

    private void capitulo1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_capitulo1ItemStateChanged
        // TODO add your handling code here:
        if (this.capitulo1.getSelectedIndex() != 0 && !this.id.getText().isEmpty()) {
            String cap = capitulo1.getSelectedItem().toString();
            llenarTabla(this.id.getText(), cap);
            llenarcolita(this.id.getText());
            mostrarimportes(cap);
        }
    }//GEN-LAST:event_capitulo1ItemStateChanged

    private void precioproyectoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioproyectoKeyReleased
        // TODO add your handling code here:
        if (!this.unidadesproyecto.getText().isEmpty() && !this.precioproyecto.getText().isEmpty()) {
            double precio = Double.parseDouble(this.precioproyecto.getText());
            double unidades = Double.parseDouble(this.unidadesproyecto.getText());
            double importepro = precio * unidades;
            this.importeproyecto.setText(String.valueOf(fr.format(importepro)));
        } else {
            this.importeproyecto.setText("");
        }

        if (!this.unidadesliquidaciones.getText().isEmpty() && !this.precioproyecto.getText().isEmpty()) {
            double precio = Double.parseDouble(this.precioproyecto.getText());
            double unidades = Double.parseDouble(this.unidadesliquidaciones.getText());
            double importepre = precio * unidades;
            this.importeliquidaciones.setText(String.valueOf(fr.format(importepre)));
        } else {
            this.importeliquidaciones.setText("");
        }

        if (!this.importeliquidaciones.getText().isEmpty() && !this.importeproyecto.getText().isEmpty()) {
            double dato = Double.parseDouble(this.importeliquidaciones.getText()) - Double.parseDouble(this.importeproyecto.getText());
            this.diferencia.setText(String.valueOf(fr.format(dato)));
        } else {
            this.diferencia.setText("");
        }
    }//GEN-LAST:event_precioproyectoKeyReleased

    private void tablaPreliquidacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPreliquidacionesMouseClicked
        // TODO add your handling code here:
        int fila = this.tablaPreliquidaciones.getSelectedRow();
        idpre.setText(this.tablaPreliquidaciones.getValueAt(fila, 0).toString());
        claseobra.setText(this.tablaPreliquidaciones.getValueAt(fila, 1).toString());
        capitulo.setSelectedItem(this.tablaPreliquidaciones.getValueAt(fila, 2).toString());
        precioproyecto.setText(this.tablaPreliquidaciones.getValueAt(fila, 3).toString());
        unidadesproyecto.setText(this.tablaPreliquidaciones.getValueAt(fila, 4).toString());
        importeproyecto.setText(this.tablaPreliquidaciones.getValueAt(fila, 5).toString());
        unidadesliquidaciones.setText(this.tablaPreliquidaciones.getValueAt(fila, 6).toString());
        importeliquidaciones.setText(this.tablaPreliquidaciones.getValueAt(fila, 7).toString());
        diferencia.setText(this.tablaPreliquidaciones.getValueAt(fila, 8).toString());
        titulo2.setText("Editar registro");
        btnGuardar.setBackground(new Color(51, 85, 193));
        btnGuardar.setText("ACTUALIZAR");
    }//GEN-LAST:event_tablaPreliquidacionesMouseClicked

    public void llenarTabla(String dato, String cap) {
        dpr = new dao_preliquidaciones();
        eliminarFilas();
        ocultar_columnas();
        llenarcolita(dato);
        mostrarimportes(cap);
        int registros = 0;
        String[] m = new String[10];
        for (Preliquidaciones p : dpr.llenarlistacircular(dpr.mostrarpreliquidaciones(dato, cap))) {
            m[0] = String.valueOf(p.getIdpreliquidacion());
            m[1] = p.getClasedeobra();
            m[2] = p.getCapitulo();
            m[3] = String.valueOf(p.getPrecioproyecto());
            m[4] = String.valueOf(p.getUnidadesproyecto());
            m[5] = String.valueOf(p.getImporteproyecto());
            m[6] = String.valueOf(p.getUnidadespreliquidaciones());
            m[7] = String.valueOf(p.getImportepreliquidaciones());
            m[8] = String.valueOf(p.getDiferencia());
            m[9] = String.valueOf(p.getIdproyecto());
            model.addRow(m);
            registros += 1;
        }
        this.totregistros.setText(String.valueOf(registros));
    }

    /*Metodo de eliminacion de las filas para que no se dupliquen los datos al mostrarlos al registrar uno nuevo*/
    public void eliminarFilas() {
        try {
            int filas = model.getRowCount();
            for (int i = 0; filas > i; i++) {
                model.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede limpiar la tabla", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /*busqueda del id del proyecto*/
    public Proyectos buscaridproyecto(String dato) {
        for (Proyectos p : dp.mostrarproyectos("")) {
            if (p.getDescripción().equals(dato)) {
                return p;
            }
        }
        return null;
    }

    /*Metodo para la lista*/
    public void llenarlista() {
        dp = new dao_proyectos();
        for (Proyectos p : dp.mostrarproyectosnocancelados()) {
            modelolista.addElement(p.getDescripción());
        }
    }

    /*metodo para buscar la clase de obra para que no se repita el dato*/
    public Preliquidaciones buscarclaseobra(String obra) {
        for (Preliquidaciones pr : dpr.llenarlistacircular(dpr.mostrarpreliquidaciones(this.id.getText(), jLabel18.getText()))) {
            if (pr.getClasedeobra().equals(obra)) {
                return pr;
            }
        }
        return null;
    }

    /*llenando la cola con todos los capitulos*/
    public void llenarcolita(String id) {
        llenarCola(dpr.mostrarcola(id));
    }

    /*llenando la cola con cada datos de los productos*/
    public ArrayList<Preliquidaciones> llenarCola(ArrayList<Preliquidaciones> a) {
        for (int i = 0; i < a.size(); i++) {
            colacapitulos.offer(a.get(i));
        }
        return colacapitulos.mostrar();
    }

    /*Metodo para sacar de la cola y actualizar el saldo de cada capitulo y los diferentes se volveran a meter*/
    public void mostrarimportes(String capitulo) {
        Preliquidaciones pr = new Preliquidaciones();
        /*variables para las importaciones*/
        double importepro = 0;
        double importepre = 0;
        double diferencia = 0;
        while (!colacapitulos.isEmpty()) {
            pr = ((Preliquidaciones) colacapitulos.poll());
            if (pr.getCapitulo().equals(capitulo)) {
                importepro += pr.getImporteproyecto();
                importepre += pr.getImportepreliquidaciones();
                diferencia += pr.getDiferencia();
            }
        }
        this.importproy.setText(String.valueOf(importepro));
        this.importpre.setText(String.valueOf(importepre));
        this.diferenciapre.setText(String.valueOf(diferencia));
    }

    /*metodo para limpiar los campos seleccionados*/
    public void limpiar() {

        this.claseobra.setText("");
        this.capitulo.setSelectedIndex(0);
        this.precioproyecto.setText("");
        this.unidadesproyecto.setText("");
        this.importeproyecto.setText("");
        this.unidadesliquidaciones.setText("");
        this.importeliquidaciones.setText("");
        this.diferencia.setText("");
        /*label para edicion del registro*/
        this.idpre.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnCancelar;
    public principal.MaterialButton btnGuardar;
    private rsbuttom.RSButtonMetro btnbuscar;
    private principal.MaterialButton btncerrar;
    public static app.bolivia.swing.JCTextField buscar;
    private javax.swing.JComboBox<String> capitulo;
    private javax.swing.JComboBox<String> capitulo1;
    public app.bolivia.swing.JCTextField claseobra;
    public app.bolivia.swing.JCTextField diferencia;
    private javax.swing.JLabel diferenciapre;
    public javax.swing.JLabel id;
    private javax.swing.JLabel idpre;
    public app.bolivia.swing.JCTextField importeliquidaciones;
    public app.bolivia.swing.JCTextField importeproyecto;
    private javax.swing.JLabel importpre;
    private javax.swing.JLabel importproy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listadoproyectos;
    private principal.MaterialButtonCircle materialButtonCircle1;
    private org.edisoncor.gui.panel.Panel panel2;
    public app.bolivia.swing.JCTextField precioproyecto;
    public static javax.swing.JTable tablaPreliquidaciones;
    public javax.swing.JLabel titulo1;
    public javax.swing.JLabel titulo2;
    public static javax.swing.JLabel totregistros;
    public app.bolivia.swing.JCTextField unidadesliquidaciones;
    public app.bolivia.swing.JCTextField unidadesproyecto;
    // End of variables declaration//GEN-END:variables
}
