/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package liquidaciones;

import Alertas.ErrordeProcesos;
import EstilodelasTablas.EstiloTablaHeader;
import EstilodelasTablas.EstiloTablaRenderer;
import EstilodelasTablas.MyScrollbarUI;
import EstilodelasTablas.MyScrollbarVistas;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import proyectos.Proyectos;
import proyectos.dao_proyectos;

/**
 *
 * @author Sony
 */
public class liquidacionesporproyecto extends javax.swing.JInternalFrame {

    /*VARIABLES PARA LLENAR LA LISTA*/
    dao_proyectos dp = new dao_proyectos();
    Proyectos proyectos = null;
    DefaultListModel modelolista;
    /*variables para las Liquidaciones*/
    DefaultTableModel model;
    dao_liquidaciones dl = new dao_liquidaciones();
    Liquidaciones liquidaciones = new Liquidaciones();

    /**
     * Creates new form NewJInternalFrame
     */
    public liquidacionesporproyecto() {
        initComponents();
        this.tablaLiquidaciones.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tablaLiquidaciones.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tablaLiquidaciones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.getVerticalScrollBar().setUI(new MyScrollbarVistas());
        jScrollPane2.getHorizontalScrollBar().setUI(new MyScrollbarVistas());
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.id.setVisible(false);
        model = (DefaultTableModel) tablaLiquidaciones.getModel();
        modelolista = new DefaultListModel();
        listadoproyectos.setModel(modelolista);
        llenarlista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialButtonCircle1 = new principal.MaterialButtonCircle();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLiquidaciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        totregistros = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jPanel5 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        id = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        listadoproyectos = new javax.swing.JList<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        importproy = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        importpre = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        diferenciapre = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btncerrar = new principal.MaterialButton();

        materialButtonCircle1.setText("materialButtonCircle1");

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tablaLiquidaciones.setBackground(new java.awt.Color(255, 255, 255));
        tablaLiquidaciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaLiquidaciones.setForeground(new java.awt.Color(255, 255, 255));
        tablaLiquidaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CAPITULO O DESCRIPCIÓN", "MONTO DEL PROYECTO", "MONTO DE LA LIQUIDACIÓN", "DIFERENCIA"
            }
        ));
        tablaLiquidaciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaLiquidaciones.setDoubleBuffered(true);
        tablaLiquidaciones.setRowHeight(20);
        tablaLiquidaciones.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaLiquidaciones.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaLiquidaciones);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 63, 84));
        jLabel2.setText("Total de Registros");

        totregistros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totregistros.setForeground(new java.awt.Color(42, 63, 84));
        totregistros.setText("0000");

        jPanel4.setBackground(new java.awt.Color(26, 187, 156));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel2.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel2MouseDragged(evt);
            }
        });
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(26, 187, 156));

        titulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("Proyectos registrados");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel6.setBorder(dropShadowBorder2);

        id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("id");

        listadoproyectos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listadoproyectosValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(listadoproyectos);

        jScrollPane4.setViewportView(jScrollPane3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(id)
                .addGap(22, 22, 22)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 334, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(42, 63, 84));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel25.setText("Totales");

        jLabel23.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(42, 63, 84));
        jLabel23.setText("Monto Proyecto:");

        importproy.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        importproy.setForeground(new java.awt.Color(26, 187, 156));
        importproy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importproy.setText("00.00");

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(42, 63, 84));
        jLabel22.setText("Monto Preliquidación:");

        importpre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        importpre.setForeground(new java.awt.Color(26, 187, 156));
        importpre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        importpre.setText("00.00");

        jLabel24.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(42, 63, 84));
        jLabel24.setText("Diferencia:");

        diferenciapre.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        diferenciapre.setForeground(new java.awt.Color(26, 187, 156));
        diferenciapre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        diferenciapre.setText("00.00");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1074, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totregistros))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(importproy, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(importpre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diferenciapre, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(importpre)
                            .addComponent(jLabel22)
                            .addComponent(importproy)
                            .addComponent(jLabel23)
                            .addComponent(diferenciapre)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totregistros))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel7);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 63, 84));
        jLabel1.setText("Liquidaciones Financieras por Proyectos");

        btncerrar.setBackground(new java.awt.Color(42, 63, 84));
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("X");
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(551, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseDragged

    }//GEN-LAST:event_panel2MouseDragged

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed

    }//GEN-LAST:event_panel2MousePressed

    private void listadoproyectosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listadoproyectosValueChanged
        // TODO add your handling code here:
        proyectos = new Proyectos();
        String dato = listadoproyectos.getSelectedValue();
        proyectos = buscaridproyecto(dato);

        String idproyecto = "";
        if (proyectos != null) {
            idproyecto = String.valueOf(proyectos.getIdproyecto());
            this.id.setText(idproyecto);
            llenarTabla(idproyecto);
            totales(idproyecto);
        } else {
            this.totregistros.setText("0");
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                er.titulo.setText("ERROR");
                er.msj.setText("PROYECTO NO ENCONTRADO");
                er.msj1.setText("");
                er.setVisible(true);
        }
    }//GEN-LAST:event_listadoproyectosValueChanged

    public void llenarTabla(String id) {
        dl = new dao_liquidaciones();
        eliminarFilas();
        int registros = 0;
        String[] m = new String[4];
        for (Liquidaciones l : dl.mostrarliquidaciones(id)) {
            m[0] = l.getCapitulo();
            m[1] = String.valueOf(l.getMontoproy());
            m[2] = String.valueOf(l.getMontopre());
            m[3] = String.valueOf(l.getDiferencia());
            model.addRow(m);
            registros += 1;
        }
        this.totregistros.setText(String.valueOf(registros));
    }

    /*Metodo de eliminacion de las filas para que no se dupliquen los datos al mostrarlos al registrar uno nuevo*/
    public void eliminarFilas() {
        try {
            int filas = model.getRowCount();
            for (int i = 0; filas > i; i++) {
                model.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede limpiar la tabla", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /*busqueda del id del proyecto*/
    public Proyectos buscaridproyecto(String dato) {
        for (Proyectos p : dp.mostrarproyectos("")) {
            if (p.getDescripción().equals(dato)) {
                return p;
            }
        }
        return null;
    }

    /*Metodo para la lista*/
    public void llenarlista() {
        dp = new dao_proyectos();
        for (Proyectos p : dp.mostrarproyectosnocancelados()) {
            modelolista.addElement(p.getDescripción());
        }
    }

    /*Metodo para obtener los montos por proyecto*/
    public void totales(String id) {
        Liquidaciones li = new Liquidaciones();
        dl = new dao_liquidaciones();
        dl.llenarpila(dl.mostrartodos());/*llenando la pila con datos*/
        double tot1 = 0;
        double tot2 = 0;
        double tot3 = 0;
        while (!dl.pilita.isEmpty()) {
            li = (Liquidaciones) dl.pilita.pop();
            if (li.getIdproyecto() == Integer.parseInt(id)) {
                tot1 += li.getMontoproy();
                tot2 += li.getMontopre();
                tot3 += li.getDiferencia();
            }
        }
        this.importproy.setText(String.valueOf(tot1));
        this.importpre.setText(String.valueOf(tot2));
        this.diferenciapre.setText(String.valueOf(tot3));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btncerrar;
    private javax.swing.JLabel diferenciapre;
    public javax.swing.JLabel id;
    private javax.swing.JLabel importpre;
    private javax.swing.JLabel importproy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> listadoproyectos;
    private principal.MaterialButtonCircle materialButtonCircle1;
    private org.edisoncor.gui.panel.Panel panel2;
    public static javax.swing.JTable tablaLiquidaciones;
    public javax.swing.JLabel titulo1;
    public static javax.swing.JLabel totregistros;
    // End of variables declaration//GEN-END:variables
}
