/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import Configuracion.configuracion;
import EstilodelasTablas.MyScrollbarUIInicio;
import InicioSesion.inicio;
import InicioSesion.iniciodesesion;
import acercade.acercade;
import alcaldes.registrodatosalcaldes;
import alcaldia.listadoalcaldias;
import clasefondo.Fondo;
import comunidades.listadocomunidades;
import departamentos.listadodepartamentos;
import donaciones.listadodonaciones;
import donantes.registrodatosdedonantes;
import java.awt.Color;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import liquidaciones.liquidacionesporproyecto;
import preliquidaciones.preliquidacionesporproyectos;
import municipios.listadomunicipios;
import proyectos.proyectosporalcaldias;
import proyectos.registrodatosproyectos;
import reportes.reportes;
import usuarios.Usuario;
import usuarios.registrodatosusuarios;
import zonas.registrozonas;

/**
 *
 * @author Sony
 */
public class menuempleado extends javax.swing.JFrame implements Runnable {

    //PARA LA EJECUCION DE LA VISTA PRINCIPAL
    Calendar calendar = Calendar.getInstance();
    //VARIABLES PARA LLEVAR CORRELATIVAMENTE LA HORA
    String hora, minutos, segundos;
    Thread hilo;
    Usuario user;
    
    //
     public static boolean cerra = false;
     public listadodepartamentos departamento=null;
     public registrozonas zonas=null;
     public registrodatosdedonantes donantes=null;
     public listadomunicipios municipios=null;
     public listadocomunidades comunidades=null;
     public registrodatosalcaldes alcaldes=null;
     public registrodatosusuarios usuarios=null;
     public listadoalcaldias alcaldias=null;
     public registrodatosproyectos proyectos=null;
     public proyectosporalcaldias proyalcaldias=null;
     public listadodonaciones donaciones=null;
     public preliquidacionesporproyectos preliquidaciones=null;
     public liquidacionesporproyecto liquidaciones=null;
     public reportes reportes=null;
      //Metodo para verificar si esta abiertas las ventanas internas
    public static boolean Cerrado(Object obj) {
        JInternalFrame[] activos = escritorio.getAllFrames();
        boolean cerrado = true;
        int i = 0;
        while (i < activos.length && cerrado) {
            if (activos[i] == obj) {
                cerrado = false;
                cerra = false;
            }
            i++;
        }
        return cerrado;
    }

    /**
     * Creates new form inicio
     */
    public menuempleado(Usuario user) {
        initComponents();
        this.user=user;
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUIInicio());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUIInicio());
        this.setTitle("Sistema para el control de Proyectos Comunitarios por Alcaldía");
        this.setLocationRelativeTo(null);
        this.setExtendedState(MAXIMIZED_BOTH);
        this.escritorio.setBorder(new Fondo("/imagenesprincipal/FondoEscritorio.png"));//agregando una imagen de fondo el escritorio
        hilo = new Thread(this);
        hilo.start();
        this.dia.setText(mostrarDia());
        this.fecha.setText(mostrarFecha());
        user1.setText(user.getUsuario());
        user2.setText(user.getUsuario());
        ocultarbotones();
    }

    private menuempleado() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        user2 = new javax.swing.JLabel();
        menuinicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        lblhora = new javax.swing.JLabel();
        footer = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblhora2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dia = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnConfiguracion = new rsbuttom.RSButtonMetro();
        rSButtonMetro2 = new rsbuttom.RSButtonMetro();
        rSButtonMetro3 = new rsbuttom.RSButtonMetro();
        rSButtonMetro4 = new rsbuttom.RSButtonMetro();
        jScrollPane1 = new javax.swing.JScrollPane();
        menuprincipal = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btninicio = new rsbuttom.RSButtonMetro();
        jPanel2 = new javax.swing.JPanel();
        btnalcaldes = new rsbuttom.RSButtonMetro();
        jPanel5 = new javax.swing.JPanel();
        btndonantes = new rsbuttom.RSButtonMetro();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnzonas = new rsbuttom.RSButtonMetro();
        btndepartamentos = new rsbuttom.RSButtonMetro();
        jPanel8 = new javax.swing.JPanel();
        rSButtonMetro14 = new rsbuttom.RSButtonMetro();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        rSButtonMetro15 = new rsbuttom.RSButtonMetro();
        rSButtonMetro18 = new rsbuttom.RSButtonMetro();
        jPanel13 = new javax.swing.JPanel();
        rSButtonMetro19 = new rsbuttom.RSButtonMetro();
        jPanel14 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        user1 = new javax.swing.JLabel();
        rSButtonMetro21 = new rsbuttom.RSButtonMetro();
        jPanel17 = new javax.swing.JPanel();
        rSButtonMetro7 = new rsbuttom.RSButtonMetro();
        rSButtonMetro8 = new rsbuttom.RSButtonMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        header.setBackground(new java.awt.Color(237, 237, 237));

        jPanel3.setBackground(new java.awt.Color(237, 237, 237));
        jPanel3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPanel3MouseMoved(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        user2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        user2.setForeground(new java.awt.Color(115, 135, 156));
        user2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user2.setText("Sony Hernández");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(user2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        menuinicio.setBackground(new java.awt.Color(42, 63, 84));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/logo.png"))); // NOI18N

        javax.swing.GroupLayout menuinicioLayout = new javax.swing.GroupLayout(menuinicio);
        menuinicio.setLayout(menuinicioLayout);
        menuinicioLayout.setHorizontalGroup(
            menuinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuinicioLayout.setVerticalGroup(
            menuinicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        lblhora.setFont(new java.awt.Font("Dialog", 1, 150)); // NOI18N
        lblhora.setForeground(new java.awt.Color(42, 63, 84));
        lblhora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblhora.setText("15:56:21");

        escritorio.setLayer(lblhora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblhora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        footer.setBackground(new java.awt.Color(255, 255, 255));
        footer.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel2.setForeground(new java.awt.Color(26, 187, 156));
        jLabel2.setText("Hora:");

        lblhora2.setForeground(new java.awt.Color(42, 63, 84));
        lblhora2.setText("12:45:78");

        jLabel8.setForeground(new java.awt.Color(26, 187, 156));
        jLabel8.setText("Fecha:");

        fecha.setForeground(new java.awt.Color(42, 63, 84));
        fecha.setText("12/45/2018");

        jLabel10.setForeground(new java.awt.Color(26, 187, 156));
        jLabel10.setText("Dìa:");

        dia.setForeground(new java.awt.Color(42, 63, 84));
        dia.setText("Lunes");

        jLabel7.setForeground(new java.awt.Color(115, 135, 156));
        jLabel7.setText("Copyright UES 2018");

        javax.swing.GroupLayout footerLayout = new javax.swing.GroupLayout(footer);
        footer.setLayout(footerLayout);
        footerLayout.setHorizontalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblhora2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        footerLayout.setVerticalGroup(
            footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(footerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, footerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblhora2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(23, 45, 68));

        btnConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Settings_20px_1.png"))); // NOI18N
        btnConfiguracion.setColorHover(new java.awt.Color(66, 85, 103));
        btnConfiguracion.setColorNormal(new java.awt.Color(23, 45, 68));
        btnConfiguracion.setColorPressed(new java.awt.Color(66, 85, 103));
        btnConfiguracion.setColorTextHover(new java.awt.Color(23, 45, 68));
        btnConfiguracion.setDefaultCapable(false);
        btnConfiguracion.setFocusable(false);
        btnConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnConfiguracion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnConfiguracion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Settings_20px_2.png"))); // NOI18N
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });

        rSButtonMetro2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Fit_to_Width_20px.png"))); // NOI18N
        rSButtonMetro2.setColorHover(new java.awt.Color(66, 85, 103));
        rSButtonMetro2.setColorNormal(new java.awt.Color(23, 45, 68));
        rSButtonMetro2.setColorPressed(new java.awt.Color(66, 85, 103));
        rSButtonMetro2.setColorTextHover(new java.awt.Color(23, 45, 68));
        rSButtonMetro2.setDefaultCapable(false);
        rSButtonMetro2.setFocusable(false);
        rSButtonMetro2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonMetro2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Fit_to_Width_20px_1.png"))); // NOI18N
        rSButtonMetro2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro2ActionPerformed(evt);
            }
        });

        rSButtonMetro3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Eye_20px.png"))); // NOI18N
        rSButtonMetro3.setColorHover(new java.awt.Color(66, 85, 103));
        rSButtonMetro3.setColorNormal(new java.awt.Color(23, 45, 68));
        rSButtonMetro3.setColorPressed(new java.awt.Color(66, 85, 103));
        rSButtonMetro3.setColorTextHover(new java.awt.Color(23, 45, 68));
        rSButtonMetro3.setDefaultCapable(false);
        rSButtonMetro3.setFocusable(false);
        rSButtonMetro3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonMetro3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Eye_20px_1.png"))); // NOI18N
        rSButtonMetro3.setVerifyInputWhenFocusTarget(false);

        rSButtonMetro4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Shutdown_20px.png"))); // NOI18N
        rSButtonMetro4.setColorHover(new java.awt.Color(66, 85, 103));
        rSButtonMetro4.setColorNormal(new java.awt.Color(23, 45, 68));
        rSButtonMetro4.setColorPressed(new java.awt.Color(66, 85, 103));
        rSButtonMetro4.setColorTextHover(new java.awt.Color(23, 45, 68));
        rSButtonMetro4.setDefaultCapable(false);
        rSButtonMetro4.setFocusable(false);
        rSButtonMetro4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonMetro4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Shutdown_20px_1.png"))); // NOI18N
        rSButtonMetro4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSButtonMetro4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(null);

        menuprincipal.setBackground(new java.awt.Color(42, 63, 84));

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("  General");

        btninicio.setForeground(new java.awt.Color(242, 245, 247));
        btninicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Home_16px.png"))); // NOI18N
        btninicio.setText("Inicio");
        btninicio.setColorHover(new java.awt.Color(55, 74, 94));
        btninicio.setColorNormal(new java.awt.Color(42, 63, 84));
        btninicio.setColorPressed(new java.awt.Color(55, 74, 94));
        btninicio.setColorTextHover(new java.awt.Color(242, 245, 247));
        btninicio.setColorTextNormal(new java.awt.Color(242, 245, 247));
        btninicio.setColorTextPressed(new java.awt.Color(242, 245, 247));
        btninicio.setDefaultCapable(false);
        btninicio.setFocusable(false);
        btninicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btninicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btninicioMouseMoved(evt);
            }
        });
        btninicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btninicioMouseExited(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        btnalcaldes.setForeground(new java.awt.Color(242, 245, 247));
        btnalcaldes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Admin_16px.png"))); // NOI18N
        btnalcaldes.setText("Alcaldes");
        btnalcaldes.setColorHover(new java.awt.Color(55, 74, 94));
        btnalcaldes.setColorNormal(new java.awt.Color(42, 63, 84));
        btnalcaldes.setColorPressed(new java.awt.Color(55, 74, 94));
        btnalcaldes.setColorTextHover(new java.awt.Color(242, 245, 247));
        btnalcaldes.setColorTextNormal(new java.awt.Color(242, 245, 247));
        btnalcaldes.setColorTextPressed(new java.awt.Color(242, 245, 247));
        btnalcaldes.setDefaultCapable(false);
        btnalcaldes.setFocusable(false);
        btnalcaldes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnalcaldes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnalcaldesMouseMoved(evt);
            }
        });
        btnalcaldes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnalcaldesMouseExited(evt);
            }
        });
        btnalcaldes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnalcaldesActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        btndonantes.setForeground(new java.awt.Color(242, 245, 247));
        btndonantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Donald_Trump_16px.png"))); // NOI18N
        btndonantes.setText("Donantes");
        btndonantes.setColorHover(new java.awt.Color(55, 74, 94));
        btndonantes.setColorNormal(new java.awt.Color(42, 63, 84));
        btndonantes.setColorPressed(new java.awt.Color(55, 74, 94));
        btndonantes.setColorTextHover(new java.awt.Color(242, 245, 247));
        btndonantes.setColorTextNormal(new java.awt.Color(242, 245, 247));
        btndonantes.setColorTextPressed(new java.awt.Color(242, 245, 247));
        btndonantes.setDefaultCapable(false);
        btndonantes.setFocusable(false);
        btndonantes.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btndonantes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndonantesMouseMoved(evt);
            }
        });
        btndonantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndonantesMouseExited(evt);
            }
        });
        btndonantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndonantesActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        btnzonas.setForeground(new java.awt.Color(242, 245, 247));
        btnzonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_World_Map_16px.png"))); // NOI18N
        btnzonas.setText("Zonas");
        btnzonas.setColorHover(new java.awt.Color(55, 74, 94));
        btnzonas.setColorNormal(new java.awt.Color(42, 63, 84));
        btnzonas.setColorPressed(new java.awt.Color(55, 74, 94));
        btnzonas.setColorTextHover(new java.awt.Color(242, 245, 247));
        btnzonas.setColorTextNormal(new java.awt.Color(242, 245, 247));
        btnzonas.setColorTextPressed(new java.awt.Color(242, 245, 247));
        btnzonas.setDefaultCapable(false);
        btnzonas.setFocusable(false);
        btnzonas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnzonas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnzonasMouseMoved(evt);
            }
        });
        btnzonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnzonasMouseExited(evt);
            }
        });
        btnzonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnzonasActionPerformed(evt);
            }
        });

        btndepartamentos.setForeground(new java.awt.Color(242, 245, 247));
        btndepartamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Spain_Map_16px.png"))); // NOI18N
        btndepartamentos.setText("Departamentos");
        btndepartamentos.setColorHover(new java.awt.Color(55, 74, 94));
        btndepartamentos.setColorNormal(new java.awt.Color(42, 63, 84));
        btndepartamentos.setColorPressed(new java.awt.Color(55, 74, 94));
        btndepartamentos.setColorTextHover(new java.awt.Color(242, 245, 247));
        btndepartamentos.setColorTextNormal(new java.awt.Color(242, 245, 247));
        btndepartamentos.setColorTextPressed(new java.awt.Color(242, 245, 247));
        btndepartamentos.setDefaultCapable(false);
        btndepartamentos.setFocusable(false);
        btndepartamentos.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btndepartamentos.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btndepartamentosMouseMoved(evt);
            }
        });
        btndepartamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btndepartamentosMouseExited(evt);
            }
        });
        btndepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepartamentosActionPerformed(evt);
            }
        });

        jPanel8.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        rSButtonMetro14.setForeground(new java.awt.Color(242, 245, 247));
        rSButtonMetro14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Map_Editing_16px.png"))); // NOI18N
        rSButtonMetro14.setText("Municipios");
        rSButtonMetro14.setColorHover(new java.awt.Color(55, 74, 94));
        rSButtonMetro14.setColorNormal(new java.awt.Color(42, 63, 84));
        rSButtonMetro14.setColorPressed(new java.awt.Color(55, 74, 94));
        rSButtonMetro14.setColorTextHover(new java.awt.Color(242, 245, 247));
        rSButtonMetro14.setColorTextNormal(new java.awt.Color(242, 245, 247));
        rSButtonMetro14.setColorTextPressed(new java.awt.Color(242, 245, 247));
        rSButtonMetro14.setDefaultCapable(false);
        rSButtonMetro14.setFocusable(false);
        rSButtonMetro14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSButtonMetro14.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rSButtonMetro14MouseMoved(evt);
            }
        });
        rSButtonMetro14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro14MouseExited(evt);
            }
        });
        rSButtonMetro14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro14ActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        rSButtonMetro15.setForeground(new java.awt.Color(242, 245, 247));
        rSButtonMetro15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Group_of_Projects_16px.png"))); // NOI18N
        rSButtonMetro15.setText("Proyectos");
        rSButtonMetro15.setColorHover(new java.awt.Color(55, 74, 94));
        rSButtonMetro15.setColorNormal(new java.awt.Color(42, 63, 84));
        rSButtonMetro15.setColorPressed(new java.awt.Color(55, 74, 94));
        rSButtonMetro15.setColorTextHover(new java.awt.Color(242, 245, 247));
        rSButtonMetro15.setColorTextNormal(new java.awt.Color(242, 245, 247));
        rSButtonMetro15.setColorTextPressed(new java.awt.Color(242, 245, 247));
        rSButtonMetro15.setDefaultCapable(false);
        rSButtonMetro15.setFocusable(false);
        rSButtonMetro15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSButtonMetro15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rSButtonMetro15MouseMoved(evt);
            }
        });
        rSButtonMetro15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rSButtonMetro15MouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro15MouseExited(evt);
            }
        });
        rSButtonMetro15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro15ActionPerformed(evt);
            }
        });

        rSButtonMetro18.setForeground(new java.awt.Color(242, 245, 247));
        rSButtonMetro18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Report_Card_16px.png"))); // NOI18N
        rSButtonMetro18.setText("Reportes");
        rSButtonMetro18.setColorHover(new java.awt.Color(55, 74, 94));
        rSButtonMetro18.setColorNormal(new java.awt.Color(42, 63, 84));
        rSButtonMetro18.setColorPressed(new java.awt.Color(55, 74, 94));
        rSButtonMetro18.setColorTextHover(new java.awt.Color(242, 245, 247));
        rSButtonMetro18.setColorTextNormal(new java.awt.Color(242, 245, 247));
        rSButtonMetro18.setColorTextPressed(new java.awt.Color(242, 245, 247));
        rSButtonMetro18.setDefaultCapable(false);
        rSButtonMetro18.setFocusable(false);
        rSButtonMetro18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSButtonMetro18.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rSButtonMetro18MouseMoved(evt);
            }
        });
        rSButtonMetro18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro18MouseExited(evt);
            }
        });
        rSButtonMetro18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro18ActionPerformed(evt);
            }
        });

        jPanel13.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        rSButtonMetro19.setForeground(new java.awt.Color(242, 245, 247));
        rSButtonMetro19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Help_16px.png"))); // NOI18N
        rSButtonMetro19.setText("Ayuda");
        rSButtonMetro19.setColorHover(new java.awt.Color(55, 74, 94));
        rSButtonMetro19.setColorNormal(new java.awt.Color(42, 63, 84));
        rSButtonMetro19.setColorPressed(new java.awt.Color(55, 74, 94));
        rSButtonMetro19.setColorTextHover(new java.awt.Color(242, 245, 247));
        rSButtonMetro19.setColorTextNormal(new java.awt.Color(242, 245, 247));
        rSButtonMetro19.setColorTextPressed(new java.awt.Color(242, 245, 247));
        rSButtonMetro19.setDefaultCapable(false);
        rSButtonMetro19.setFocusable(false);
        rSButtonMetro19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSButtonMetro19.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rSButtonMetro19MouseMoved(evt);
            }
        });
        rSButtonMetro19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro19MouseExited(evt);
            }
        });
        rSButtonMetro19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro19ActionPerformed(evt);
            }
        });

        jPanel14.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Admin_60px.png"))); // NOI18N

        jLabel6.setForeground(new java.awt.Color(186, 184, 180));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bienvenido");

        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user1.setText("Sony Hernández");

        rSButtonMetro21.setForeground(new java.awt.Color(242, 245, 247));
        rSButtonMetro21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/icons8_Info_16px.png"))); // NOI18N
        rSButtonMetro21.setText("Acerca de");
        rSButtonMetro21.setColorHover(new java.awt.Color(55, 74, 94));
        rSButtonMetro21.setColorNormal(new java.awt.Color(42, 63, 84));
        rSButtonMetro21.setColorPressed(new java.awt.Color(55, 74, 94));
        rSButtonMetro21.setColorTextHover(new java.awt.Color(242, 245, 247));
        rSButtonMetro21.setColorTextNormal(new java.awt.Color(242, 245, 247));
        rSButtonMetro21.setColorTextPressed(new java.awt.Color(242, 245, 247));
        rSButtonMetro21.setDefaultCapable(false);
        rSButtonMetro21.setFocusable(false);
        rSButtonMetro21.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        rSButtonMetro21.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                rSButtonMetro21MouseMoved(evt);
            }
        });
        rSButtonMetro21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro21MouseExited(evt);
            }
        });
        rSButtonMetro21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro21ActionPerformed(evt);
            }
        });

        jPanel17.setBackground(new java.awt.Color(42, 63, 84));

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        rSButtonMetro7.setText("Registrar proyectos");
        rSButtonMetro7.setColorHover(new java.awt.Color(57, 86, 115));
        rSButtonMetro7.setColorNormal(new java.awt.Color(55, 74, 94));
        rSButtonMetro7.setColorPressed(new java.awt.Color(57, 86, 115));
        rSButtonMetro7.setColorTextHover(new java.awt.Color(255, 255, 255));
        rSButtonMetro7.setDefaultCapable(false);
        rSButtonMetro7.setFocusable(false);
        rSButtonMetro7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rSButtonMetro7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonMetro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro7ActionPerformed(evt);
            }
        });

        rSButtonMetro8.setBackground(new java.awt.Color(55, 74, 94));
        rSButtonMetro8.setText("Proyectos por alcaldías");
        rSButtonMetro8.setColorHover(new java.awt.Color(57, 86, 115));
        rSButtonMetro8.setColorNormal(new java.awt.Color(55, 74, 94));
        rSButtonMetro8.setColorPressed(new java.awt.Color(57, 86, 115));
        rSButtonMetro8.setColorTextHover(new java.awt.Color(255, 255, 255));
        rSButtonMetro8.setDefaultCapable(false);
        rSButtonMetro8.setFocusable(false);
        rSButtonMetro8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        rSButtonMetro8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rSButtonMetro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuprincipalLayout = new javax.swing.GroupLayout(menuprincipal);
        menuprincipal.setLayout(menuprincipalLayout);
        menuprincipalLayout.setHorizontalGroup(
            menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSButtonMetro21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSButtonMetro19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSButtonMetro18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSButtonMetro15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSButtonMetro14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btndepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btninicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnalcaldes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnzonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btndonantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(user1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(rSButtonMetro7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(rSButtonMetro8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuprincipalLayout.setVerticalGroup(
            menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuprincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(menuprincipalLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(user1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(12, 12, 12)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btninicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnalcaldes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndonantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnzonas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btndepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSButtonMetro14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSButtonMetro15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(rSButtonMetro7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(rSButtonMetro8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSButtonMetro18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSButtonMetro19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(menuprincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rSButtonMetro21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(370, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(menuprincipal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(menuinicio, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(escritorio)
                    .addComponent(footer, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menuinicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(escritorio)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(237, 237, 237));
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseMoved
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(217, 222, 228));
    }//GEN-LAST:event_jPanel3MouseMoved

    private void rSButtonMetro2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro2ActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_rSButtonMetro2ActionPerformed

    private void rSButtonMetro4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro4ActionPerformed
        // TODO add your handling code here:
        iniciodesesion is = new iniciodesesion();
        is.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButtonMetro4ActionPerformed

    private void btninicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseExited
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_btninicioMouseExited

    private void btninicioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btninicioMouseMoved
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_btninicioMouseMoved

    private void btnalcaldesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnalcaldesMouseExited
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_btnalcaldesMouseExited

    private void btnalcaldesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnalcaldesMouseMoved
        // TODO add your handling code here:
        jPanel5.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_btnalcaldesMouseMoved

    private void btndonantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndonantesMouseExited
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_btndonantesMouseExited

    private void btndonantesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndonantesMouseMoved
        // TODO add your handling code here:
        jPanel6.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_btndonantesMouseMoved

    private void btnzonasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnzonasMouseExited
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_btnzonasMouseExited

    private void btnzonasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnzonasMouseMoved
        // TODO add your handling code here:
        jPanel7.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_btnzonasMouseMoved

    private void btndepartamentosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepartamentosMouseExited
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_btndepartamentosMouseExited

    private void btndepartamentosMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btndepartamentosMouseMoved
        // TODO add your handling code here:
        jPanel8.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_btndepartamentosMouseMoved

    private void rSButtonMetro14MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro14MouseExited
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_rSButtonMetro14MouseExited

    private void rSButtonMetro14MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro14MouseMoved
        // TODO add your handling code here:
        jPanel9.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_rSButtonMetro14MouseMoved

    private void rSButtonMetro15MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro15MouseExited
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_rSButtonMetro15MouseExited

    private void rSButtonMetro15MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro15MouseMoved
        // TODO add your handling code here:
        jPanel10.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_rSButtonMetro15MouseMoved

    private void rSButtonMetro18MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro18MouseExited
        // TODO add your handling code here:
        jPanel13.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_rSButtonMetro18MouseExited

    private void rSButtonMetro18MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro18MouseMoved
        // TODO add your handling code here:
        jPanel13.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_rSButtonMetro18MouseMoved

    private void rSButtonMetro19MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro19MouseExited
        // TODO add your handling code here:
         jPanel14.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_rSButtonMetro19MouseExited

    private void rSButtonMetro19MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro19MouseMoved
        // TODO add your handling code here:
        jPanel14.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_rSButtonMetro19MouseMoved

    private void btndepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepartamentosActionPerformed
        // TODO add your handling code here:
         if (Cerrado(departamento)) {
            departamento=new listadodepartamentos();
            departamento.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            departamento.setSize(width, Height);
            escritorio.add(departamento);
            departamento.show();
        }
    }//GEN-LAST:event_btndepartamentosActionPerformed

    private void btnzonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzonasActionPerformed
        // TODO add your handling code here:
         if (Cerrado(zonas)) {
            zonas=new registrozonas();
            zonas.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            zonas.setSize(width, Height);
            escritorio.add(zonas);
            zonas.show();
        }
    }//GEN-LAST:event_btnzonasActionPerformed

    private void rSButtonMetro21MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro21MouseMoved
        // TODO add your handling code here:
         jPanel17.setBackground(new Color(26, 187, 156));
    }//GEN-LAST:event_rSButtonMetro21MouseMoved

    private void rSButtonMetro21MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro21MouseExited
        // TODO add your handling code here:
         jPanel17.setBackground(new Color(42, 63, 84));
    }//GEN-LAST:event_rSButtonMetro21MouseExited

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        // TODO add your handling code here:
        configuracion con=new configuracion(new JFrame(), true);
        con.setVisible(true);
        con.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btndonantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndonantesActionPerformed
        // TODO add your handling code here:
         if (Cerrado(donantes)) {
            donantes=new registrodatosdedonantes();
            donantes.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            donantes.setSize(width, Height);
            escritorio.add(donantes);
            donantes.show();
        }
    }//GEN-LAST:event_btndonantesActionPerformed

    private void rSButtonMetro14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro14ActionPerformed
        // TODO add your handling code here:
        if (Cerrado(municipios)) {
            municipios=new listadomunicipios();
            municipios.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            municipios.setSize(width, Height);
            escritorio.add(municipios);
            municipios.show();
        }
    }//GEN-LAST:event_rSButtonMetro14ActionPerformed

    private void btnalcaldesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnalcaldesActionPerformed
        // TODO add your handling code here:
        if (Cerrado(alcaldes)) {
            alcaldes=new registrodatosalcaldes();
            alcaldes.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            alcaldes.setSize(width, Height);
            escritorio.add(alcaldes);
            alcaldes.show();
        }
    }//GEN-LAST:event_btnalcaldesActionPerformed

    private void rSButtonMetro15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro15ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rSButtonMetro15ActionPerformed

    private void rSButtonMetro21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro21ActionPerformed
        // TODO add your handling code here:
        acercade ac=new acercade();
        ac.setVisible(true);
    }//GEN-LAST:event_rSButtonMetro21ActionPerformed

    private void rSButtonMetro15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro15MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            rSButtonMetro7.setVisible(true);
            rSButtonMetro8.setVisible(true);
        }else if(evt.getClickCount()==1){
            rSButtonMetro7.setVisible(false);
            rSButtonMetro8.setVisible(false);
        }
    }//GEN-LAST:event_rSButtonMetro15MouseClicked

    private void rSButtonMetro19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro19ActionPerformed
        // TODO add your handling code here:
        String fileLocal=new String("src/ayuda/Manual.pdf");
        try {
            Runtime.getRuntime().exec("cmd /c start "+fileLocal);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_rSButtonMetro19ActionPerformed

    private void rSButtonMetro18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro18ActionPerformed
        // TODO add your handling code here:
        
        if (Cerrado(reportes)) {
            reportes=new reportes();
            reportes.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            reportes.setSize(width, Height);
            escritorio.add(reportes);
            reportes.show();
        }
    }//GEN-LAST:event_rSButtonMetro18ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        // TODO add your handling code here:
        if (Cerrado(proyectos)) {
            proyectos=new registrodatosproyectos();
            proyectos.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            proyectos.setSize(width, Height);
            escritorio.add(proyectos);
            proyectos.show();
            registrodatosproyectos.usuario.setText(user.getNombre()+" "+user.getApellidos());
            registrodatosproyectos.idusuario.setText(String.valueOf(user.getIdpersona()));
        }
    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void rSButtonMetro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro8ActionPerformed
        // TODO add your handling code here:
         if (Cerrado(proyalcaldias)) {
            proyalcaldias=new proyectosporalcaldias();
            proyalcaldias.setMaximizable(true);
            int width = escritorio.getWidth();
            int Height = escritorio.getHeight();
            proyalcaldias.setSize(width, Height);
            escritorio.add(proyalcaldias);
            proyalcaldias.show();
        }
    }//GEN-LAST:event_rSButtonMetro8ActionPerformed

    //METODOS PARA MOSTRAR DIA ACTUAL,FECHA ACTUAL, Y LA HORA ACTUAL
    public String mostrarFecha() {
        Date fecha = new Date();
        //FORMATO PARA LA FECHA
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/YYYY");
        return format.format(fecha);

    }

    public String mostrarDia() {

        String diaActual = null;
        int dia;
        dia = calendar.get(Calendar.DAY_OF_WEEK);
        switch (dia) {
            case 1:
                diaActual = "Domingo";
                break;
            case 2:
                diaActual = "Lunes";
                break;
            case 3:
                diaActual = "Martes";
                break;
            case 4:
                diaActual = "Miercoles";
                break;
            case 5:
                diaActual = "Jueves";
                break;
            case 6:
                diaActual = "Viernes";
                break;
            case 7:
                diaActual = "Sabado";
                break;
        }
        return diaActual;
    }

    public void mostrarHora() {
        Calendar calendario = new GregorianCalendar();
        Date horaActual = new Date();
        calendario.setTime(horaActual);
        hora = calendario.get(Calendar.HOUR_OF_DAY) > 9 ? "" + calendario.get(Calendar.HOUR_OF_DAY) : "0" + calendario.get(Calendar.HOUR_OF_DAY);
        minutos = calendario.get(Calendar.MINUTE) > 9 ? "" + calendario.get(Calendar.MINUTE) : "0" + calendario.get(Calendar.MINUTE);
        segundos = calendario.get(Calendar.SECOND) > 9 ? "" + calendario.get(Calendar.SECOND) : "0" + calendario.get(Calendar.SECOND);
    }

    public void run() {
        Thread correr = Thread.currentThread();
        while (correr == hilo) {
            mostrarHora();
            this.lblhora.setText(hora + ":" + minutos + ":" + segundos);
            this.lblhora2.setText(hora + ":" + minutos + ":" + segundos);
        }
    }
    
    public void ocultarbotones(){
        rSButtonMetro7.setVisible(false);
        rSButtonMetro8.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuempleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuempleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro btnConfiguracion;
    public static rsbuttom.RSButtonMetro btnalcaldes;
    public static rsbuttom.RSButtonMetro btndepartamentos;
    public static rsbuttom.RSButtonMetro btndonantes;
    public static rsbuttom.RSButtonMetro btninicio;
    public static rsbuttom.RSButtonMetro btnzonas;
    private javax.swing.JLabel dia;
    public static javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel fecha;
    public static javax.swing.JPanel footer;
    public static javax.swing.JPanel header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblhora;
    private javax.swing.JLabel lblhora2;
    public static javax.swing.JPanel menuinicio;
    public static javax.swing.JPanel menuprincipal;
    private rsbuttom.RSButtonMetro rSButtonMetro14;
    private rsbuttom.RSButtonMetro rSButtonMetro15;
    private rsbuttom.RSButtonMetro rSButtonMetro18;
    private rsbuttom.RSButtonMetro rSButtonMetro19;
    private rsbuttom.RSButtonMetro rSButtonMetro2;
    private rsbuttom.RSButtonMetro rSButtonMetro21;
    private rsbuttom.RSButtonMetro rSButtonMetro3;
    private rsbuttom.RSButtonMetro rSButtonMetro4;
    private rsbuttom.RSButtonMetro rSButtonMetro7;
    private rsbuttom.RSButtonMetro rSButtonMetro8;
    public static javax.swing.JLabel user1;
    public static javax.swing.JLabel user2;
    // End of variables declaration//GEN-END:variables
}
