/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InicioSesion;

import Alertas.ErrordeProcesos;
import Alertas.ProcesoExitoso;
import Recursividad.Recursividad;
import java.sql.Date;
import java.util.Calendar;
import javax.swing.JFrame;
import persona.Persona;
import persona.dao_persona;
import usuarios.Encriptacion;
import usuarios.Usuario;
import usuarios.dao_usuarios;

/**
 *
 * @author Sony
 */
public class crearcuenta extends javax.swing.JFrame {

    dao_usuarios du = new dao_usuarios();
    Usuario usuarios = new Usuario();
    Usuario usuarios1 = new Usuario();
    Persona persona = new Persona();
    dao_persona dp = new dao_persona();

    /**
     * Creates new form LoginUi
     */
    public crearcuenta() {
        initComponents();
        this.setTitle("Sistema para el control de Proyectos Comunitarios por Alcaldía");
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.sexgroup.add(this.m);
        this.sexgroup.add(this.f);
        iduser.setVisible(false);
        this.iduser.setText(String.valueOf(generarnumero()));
        this.fecha.setSelectableDateRange(null, new java.util.Date());
        this.codigo.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sexgroup = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        j1 = new javax.swing.JLabel();
        j2 = new javax.swing.JLabel();
        j3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btniniciosesion = new rsbuttom.RSButtonMetro();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codigo = new app.bolivia.swing.JCTextField();
        jLabel9 = new javax.swing.JLabel();
        j4 = new javax.swing.JLabel();
        j5 = new javax.swing.JLabel();
        j6 = new javax.swing.JLabel();
        j7 = new javax.swing.JLabel();
        j8 = new javax.swing.JLabel();
        j9 = new javax.swing.JLabel();
        usuario = new app.bolivia.swing.JCTextField();
        j10 = new javax.swing.JLabel();
        contrasena = new jpass.JRPasswordField();
        j11 = new javax.swing.JLabel();
        m = new javax.swing.JRadioButton();
        f = new javax.swing.JRadioButton();
        fecha = new com.toedter.calendar.JDateChooser();
        tipo = new javax.swing.JComboBox<>();
        nit = new javax.swing.JFormattedTextField();
        dui = new javax.swing.JFormattedTextField();
        nombre = new app.bolivia.swing.JCTextField();
        apellido = new app.bolivia.swing.JCTextField();
        profesion = new app.bolivia.swing.JCTextField();
        iduser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(247, 247, 247));
        jPanel2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(247, 247, 247));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(115, 135, 156));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nueva Cuenta");

        j1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j1.setForeground(new java.awt.Color(153, 153, 153));
        j1.setText("Codigo:");

        j2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j2.setForeground(new java.awt.Color(153, 153, 153));
        j2.setText("Nombres:");

        j3.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j3.setForeground(new java.awt.Color(153, 153, 153));
        j3.setText("Apellidos:");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("____________________");

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("____________________");

        btniniciosesion.setText("Registrar");
        btniniciosesion.setColorHover(new java.awt.Color(22, 159, 133));
        btniniciosesion.setColorNormal(new java.awt.Color(38, 185, 154));
        btniniciosesion.setColorPressed(new java.awt.Color(22, 159, 133));
        btniniciosesion.setColorTextHover(new java.awt.Color(255, 255, 255));
        btniniciosesion.setDefaultCapable(false);
        btniniciosesion.setFocusable(false);
        btniniciosesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btniniciosesion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btniniciosesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btniniciosesionActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("___________________________________________________________________________________________________________");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(115, 135, 156));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Interstellar");

        jLabel5.setForeground(new java.awt.Color(115, 135, 156));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Volver");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(115, 135, 156));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sistema para el control de información de Proyectos Comunitarios");

        jLabel8.setForeground(new java.awt.Color(115, 135, 156));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("de cada Alcaldía de el país El Salvador");

        codigo.setBackground(new java.awt.Color(247, 247, 247));
        codigo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        codigo.setForeground(new java.awt.Color(153, 153, 153));
        codigo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        codigo.setPlaceholder("Codigo");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesprincipal/logoinicio.png"))); // NOI18N

        j4.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j4.setForeground(new java.awt.Color(153, 153, 153));
        j4.setText("Fecha Nacimiento:");

        j5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j5.setForeground(new java.awt.Color(153, 153, 153));
        j5.setText("Dui:");

        j6.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j6.setForeground(new java.awt.Color(153, 153, 153));
        j6.setText("Nit:");

        j7.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j7.setForeground(new java.awt.Color(153, 153, 153));
        j7.setText("Profesión:");

        j8.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j8.setForeground(new java.awt.Color(153, 153, 153));
        j8.setText("Sexo:");

        j9.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j9.setForeground(new java.awt.Color(153, 153, 153));
        j9.setText("Usuario:");

        usuario.setBackground(new java.awt.Color(247, 247, 247));
        usuario.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        usuario.setForeground(new java.awt.Color(153, 153, 153));
        usuario.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        usuario.setPlaceholder("Usuario");

        j10.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j10.setForeground(new java.awt.Color(153, 153, 153));
        j10.setText("Contraseña:");

        contrasena.setBackground(new java.awt.Color(247, 247, 247));
        contrasena.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        contrasena.setForeground(new java.awt.Color(153, 153, 153));
        contrasena.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        contrasena.setPlaceholder("Contraseña");

        j11.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        j11.setForeground(new java.awt.Color(153, 153, 153));
        j11.setText("Tipo:");

        m.setBackground(new java.awt.Color(207, 207, 207));
        m.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        m.setText("Masculino");
        m.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        f.setBackground(new java.awt.Color(207, 207, 207));
        f.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        f.setText("Femenino");
        f.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        fecha.setBackground(new java.awt.Color(247, 247, 247));
        fecha.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        tipo.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Administrador", "Empleado" }));
        tipo.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));

        nit.setBackground(new java.awt.Color(247, 247, 247));
        nit.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        nit.setForeground(new java.awt.Color(153, 153, 153));
        try {
            nit.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-######-###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        nit.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        dui.setBackground(new java.awt.Color(247, 247, 247));
        dui.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        dui.setForeground(new java.awt.Color(153, 153, 153));
        try {
            dui.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        dui.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N

        nombre.setBackground(new java.awt.Color(247, 247, 247));
        nombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        nombre.setForeground(new java.awt.Color(153, 153, 153));
        nombre.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        nombre.setPlaceholder("Nombres");

        apellido.setBackground(new java.awt.Color(247, 247, 247));
        apellido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        apellido.setForeground(new java.awt.Color(153, 153, 153));
        apellido.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        apellido.setPlaceholder("Apellidos");
        apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                apellidoKeyReleased(evt);
            }
        });

        profesion.setBackground(new java.awt.Color(247, 247, 247));
        profesion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        profesion.setForeground(new java.awt.Color(153, 153, 153));
        profesion.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        profesion.setPlaceholder("Profesión");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(61, 61, 61))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btniniciosesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fecha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(nit, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(dui, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addGap(0, 0, Short.MAX_VALUE)
                                                        .addComponent(profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(usuario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(j10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(contrasena, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(j11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(m)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(f)))))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dui, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(j4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(j9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(j5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(j6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(j7, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addComponent(j8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(f, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(btniniciosesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        jPanel2.add(jPanel1);
        jPanel1.setBounds(310, 20, 760, 660);

        iduser.setText("jLabel10");
        jPanel2.add(iduser);
        iduser.setBounds(180, 170, 48, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1256, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btniniciosesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btniniciosesionActionPerformed
        // TODO add your handling code here:
        if (!this.iduser.getText().isEmpty() && !this.nombre.getText().isEmpty() && !this.apellido.getText().isEmpty()
                && this.fecha.getDate() != null && !this.dui.getText().isEmpty() && !this.nit.getText().isEmpty()
                && !this.profesion.getText().isEmpty() && !this.usuario.getText().isEmpty() && this.tipo.getSelectedIndex() != 0) {
            this.iduser.setText(String.valueOf(generarnumero()));
            Calendar cal;
            int d, m, a;
            cal = this.fecha.getCalendar();
            d = cal.get(Calendar.DAY_OF_MONTH);
            m = cal.get(Calendar.MONTH);
            a = cal.get(Calendar.YEAR) - 1900;

            String nombre = this.nombre.getText();
            String apellido = this.apellido.getText();

            String dui = this.dui.getText();
            String nit = this.nit.getText();
            String profesion = this.profesion.getText();
            String sexo = "";
            if (this.m.isSelected()) {
                sexo = "Masculino";
            } else if (this.f.isSelected()) {
                sexo = "Femenino";
            }
            String usuario = this.usuario.getText();
            String contrasena = this.contrasena.getText();
            String passencrip = Encriptacion.getStringMessageDigest(contrasena, Encriptacion.MD5);
            String tipo = this.tipo.getSelectedItem().toString();

            String codigo = this.codigo.getText();
            int iduser = Integer.parseInt(this.iduser.getText());

            usuarios.setCodigo(codigo);
            usuarios.setNombre(nombre);
            usuarios.setApellidos(apellido);
            usuarios.setFechanacimiento(new Date(a, m, d));
            usuarios.setDui(dui);
            usuarios.setNit(nit);
            usuarios.setProfesion(profesion);
            usuarios.setSexo(sexo);
            usuarios.setUsuario(usuario);
            usuarios.setContraseña(passencrip);
            usuarios.setTipouser(tipo);

            persona = buscarduinit(dui, nit);
            usuarios1 = buscaruser(usuario);
            usuarios.setIdpersona(iduser);
            if (persona == null) {
                if (usuarios1 == null) {
                    du.insertar(usuarios);
                    ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                    er.titulo.setText("REGSITRO GUARDADO");
                    er.msj.setText("REGSITRO INGRESADO");
                    er.msj1.setText("SATISFACTORIAMENTE");
                    er.setVisible(true);
                    limpiar();
                } else {
                    ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                    er.titulo.setText("ERROR");
                    er.msj.setText("EL USUARIOS YA HA SIDO INGRESADO");
                    er.msj1.setText("POR FAVOR INGRESE OTRO");
                    er.setVisible(true);
                }
            } else {
                ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                er.titulo.setText("ERROR");
                er.msj.setText("EL DUI Ó NIT YA HAN SIDO INGRESADO");
                er.msj1.setText("POR FAVOR INGRESE OTRO");
                er.setVisible(true);
            }

        } else {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("CAMPOS VACÍOS");
            er.msj.setText("POR FAVOR LLENE LOS CAMPOS");
            er.msj1.setText("SOLICITADOS");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btniniciosesionActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
        iniciodesesion is = new iniciodesesion();
        is.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void apellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_apellidoKeyReleased
        // TODO add your handling code here:
        String dato = apellido.getText();
        if (!dato.equals("")) {
            String d = Recursividad.oneend(dato, 0);
            this.codigo.setText(d.toUpperCase() + String.valueOf(Recursividad.tresdigitos()));
        } else {
            this.codigo.setText("");
        }
    }//GEN-LAST:event_apellidoKeyReleased

    public int generarnumero() {
        int n = 0;
        if (dp.datospersona().size() > 0) {
            n = dp.datospersona().get(dp.datospersona().size() - 1).getIdpersona() + 1;
        } else {
            n = 1;
        }

        return n;
    }

    /*metodo de la busqueda de usuarios existentes para que no hallan repeticiones*/
    public Usuario buscaruser(String usuario) {
        for (Usuario u : du.llenaravl(du.datosusuarios())) {
            if (u.getUsuario().equals(usuario)) {
                return u;
            }
        }
        return null;
    }

    /*Metodo para la busqueda de el dui y el nit para que no hallan registros repetidos*/
    public Persona buscarduinit(String dui, String nit) {
        for (Persona p : dp.datospersona()) {
            if (p.getDui().equals(dui) || p.getNit().equals(nit)) {
                return p;
            }
        }
        return null;
    }

    /*Metodo para limpiar los campos*/
    public void limpiar() {

        this.codigo.setText("");
        this.nombre.setText("");
        this.apellido.setText("");
        this.fecha.setDate(null);
        this.dui.setText("");
        this.nit.setText("");
        this.profesion.setText("");
        this.sexgroup.clearSelection();
        this.usuario.setText("");
        this.contrasena.setText("");
        this.tipo.setSelectedIndex(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(crearcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(crearcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(crearcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(crearcuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new crearcuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static app.bolivia.swing.JCTextField apellido;
    private rsbuttom.RSButtonMetro btniniciosesion;
    public static app.bolivia.swing.JCTextField codigo;
    public static jpass.JRPasswordField contrasena;
    private javax.swing.JFormattedTextField dui;
    private javax.swing.JRadioButton f;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JLabel iduser;
    private javax.swing.JLabel j1;
    private javax.swing.JLabel j10;
    private javax.swing.JLabel j11;
    private javax.swing.JLabel j2;
    private javax.swing.JLabel j3;
    private javax.swing.JLabel j4;
    private javax.swing.JLabel j5;
    private javax.swing.JLabel j6;
    private javax.swing.JLabel j7;
    private javax.swing.JLabel j8;
    private javax.swing.JLabel j9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton m;
    private javax.swing.JFormattedTextField nit;
    public static app.bolivia.swing.JCTextField nombre;
    public static app.bolivia.swing.JCTextField profesion;
    private javax.swing.ButtonGroup sexgroup;
    private javax.swing.JComboBox<String> tipo;
    public static app.bolivia.swing.JCTextField usuario;
    // End of variables declaration//GEN-END:variables
}
