/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package comunidades;

import Alertas.AlertadeEliminacion;
import Alertas.ErrordeProcesos;
import Alertas.ProcesoExitoso;
import EstilodelasTablas.EstiloTablaHeader;
import EstilodelasTablas.EstiloTablaRenderer;
import EstilodelasTablas.MyScrollbarUI;
import EstilodelasTablas.MyScrollbarVistas;
import ListasDobles.Nodo;
import Recursividad.Recursividad;
import Validaciones.Validaciones;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import municipios.Municipio;
import municipios.dao_municipios;
import proyectos.Proyectos;

/**
 *
 * @author Sony
 */
public class listadocomunidades extends javax.swing.JInternalFrame {

    /*Para el combo y el id de los municipios*/
    dao_municipios muni = new dao_municipios();
    Municipio municipio = new Municipio();
    /*Para el registro de las comunidades*/
    dao_comunidades comuni = new dao_comunidades();
    DefaultTableModel modelo;
    Comunidades comunidades;
    Comunidades comunidades1 = new Comunidades();

    /*para la eliminacion*/
    Proyectos proyec = new Proyectos();
    Validaciones validar = new Validaciones();

    /**
     * Creates new form NewJInternalFrame
     */
    public listadocomunidades() {
        initComponents();
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.getVerticalScrollBar().setUI(new MyScrollbarVistas());
        jScrollPane2.getHorizontalScrollBar().setUI(new MyScrollbarVistas());
        this.tablaComunidades.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tablaComunidades.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tablaComunidades.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        modelo = (DefaultTableModel) tablaComunidades.getModel();
        llenarTabla();
        llenarcombomunicipios();
        this.id.setVisible(false);
        this.codigo.setEditable(false);
        titulo.setText("Nuevo registro");
    }

    void ocultar_columnas() {
        this.tablaComunidades.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tablaComunidades.getColumnModel().getColumn(0).setMinWidth(0);
        this.tablaComunidades.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaComunidades = new javax.swing.JTable();
        btneditar = new principal.MaterialButton();
        btneliminar = new principal.MaterialButton();
        buscar = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        totregistros = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel1 = new org.edisoncor.gui.panel.Panel();
        jPanel3 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombre = new app.bolivia.swing.JCTextField();
        codigo = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        combomunicipios = new javax.swing.JComboBox<>();
        btnCancelar = new principal.MaterialButton();
        btnGuardar = new principal.MaterialButton();
        btnbuscar = new rsbuttom.RSButtonMetro();
        jLabel1 = new javax.swing.JLabel();
        btncerrar = new principal.MaterialButton();

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tablaComunidades.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaComunidades.setForeground(new java.awt.Color(255, 255, 255));
        tablaComunidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CÓDIGO", "NOMBRE", "MUNICIPIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaComunidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaComunidades.setDoubleBuffered(true);
        tablaComunidades.setRowHeight(20);
        tablaComunidades.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaComunidades.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaComunidades);
        if (tablaComunidades.getColumnModel().getColumnCount() > 0) {
            tablaComunidades.getColumnModel().getColumn(0).setMinWidth(70);
            tablaComunidades.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        btneditar.setBackground(new java.awt.Color(51, 85, 193));
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setText("EDITAR");
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(243, 156, 17));
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("ELIMINAR");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        buscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(26, 187, 156)));
        buscar.setForeground(new java.awt.Color(26, 187, 156));
        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setPlaceholder("BUSCAR COMUNIDAD");
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 63, 84));
        jLabel2.setText("Total de Registros");

        totregistros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totregistros.setForeground(new java.awt.Color(42, 63, 84));
        totregistros.setText("0000");

        jPanel2.setBackground(new java.awt.Color(26, 187, 156));

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel1.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel1MouseDragged(evt);
            }
        });
        panel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel1MousePressed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(26, 187, 156));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("TITULO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel4.setBorder(dropShadowBorder2);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 187, 156));
        jLabel7.setText("Municipio:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 187, 156));
        jLabel11.setText("Nombre:");

        nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 187, 156));
        jLabel8.setText("Código:");

        id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("id");

        combomunicipios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(144, 144, 144)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel11)
                    .addComponent(jLabel7))
                .addGap(54, 54, 54)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(codigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(combomunicipios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(212, 212, 212)
                .addComponent(jLabel5)
                .addGap(352, 352, 352)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel5)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(combomunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(74, 74, 74))
        );

        btnCancelar.setBackground(new java.awt.Color(243, 156, 17));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(26, 187, 156));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setToolTipText("");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDonantes/icons8_Search_30px.png"))); // NOI18N
        btnbuscar.setColorHover(new java.awt.Color(229, 226, 229));
        btnbuscar.setColorNormal(new java.awt.Color(255, 255, 255));
        btnbuscar.setColorPressed(new java.awt.Color(248, 246, 246));
        btnbuscar.setColorTextHover(new java.awt.Color(248, 246, 246));
        btnbuscar.setDefaultCapable(false);
        btnbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totregistros))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totregistros))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(jPanel7);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 63, 84));
        jLabel1.setText("Listado de Comunidades");

        btncerrar.setBackground(new java.awt.Color(42, 63, 84));
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("X");
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (this.tablaComunidades.getRowCount() < 1) {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("LA TABLA ESTA VACÍA");
            er.msj1.setText("");
            er.setVisible(true);
        } else {
            if (this.tablaComunidades.getSelectedRowCount() < 1) {
                ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                int fila = this.tablaComunidades.getSelectedRow();
                int ideliminar = Integer.parseInt(this.tablaComunidades.getValueAt(fila, 0).toString());
                proyec = validar.buscaruser(0, ideliminar,0);
                if (proyec == null) {
                    AlertadeEliminacion wa = new AlertadeEliminacion(new JFrame(), true);
                    wa.titulo.setText("¿ESTAS SEGURO?");
                    wa.msj.setText("SE BORRARA PERMANENTEMENTE");
                    wa.msj1.setText("EL REGISTRO SELECCIONADO");
                    wa.setVisible(true);
                    if (AlertadeEliminacion.salir == true) {
                        wa.nombre.setText(this.tablaComunidades.getValueAt(fila, 2).toString());/*agarrando el dato del nombre de la tabla para proceder 
                    a la busqueda para eliminarlo con la lista circular doble*/
                        comunidades = new Comunidades(wa.nombre.getText());
                        Nodo dato = comuni.ldc.Eliminar(comunidades);/*salvando el registro eliminado de la lista*/
                        if (dato != null) {
                            comuni.eliminar((Comunidades) dato.getDato());/*eliminando el registro de la base de datos*/
                            llenarTabla();
                            ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                            er.titulo.setText("");
                            er.msj.setText("REGSITRO ELIMINADO");
                            er.msj1.setText("SATISFACTORIAMENTE");
                            er.setVisible(true);
                        } else {
                            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                            er.titulo.setText("OOPS...");
                            er.msj.setText("EL REGISTRO NO SE");
                            er.msj1.setText("PUDO ELIMINAR");
                            er.setVisible(true);
                        }
                    }
                } else {
                    ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                    er.titulo.setText("OOPS...");
                    er.msj.setText("ESTE REGISTRO NO SE");
                    er.msj1.setText("PUEDE ELIMINAR");
                    er.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
//        dep.consultadepartamentos();
//        llenarTabla();
    }//GEN-LAST:event_buscarKeyReleased

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        if (this.tablaComunidades.getRowCount() < 1) {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("NO HAY REGISTROS");
            er.msj1.setText("");
            er.setVisible(true);
        } else {
            if (this.tablaComunidades.getSelectedRowCount() < 1) {
                ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                int fila = this.tablaComunidades.getSelectedRow();
                id.setText(this.tablaComunidades.getValueAt(fila, 0).toString());
                codigo.setText(this.tablaComunidades.getValueAt(fila, 1).toString());
                nombre.setText(this.tablaComunidades.getValueAt(fila, 2).toString());
                combomunicipios.setSelectedItem(this.tablaComunidades.getValueAt(fila, 3));
                titulo.setText("Editar registro");
                btnGuardar.setBackground(new Color(51, 85, 193));
                btnGuardar.setText("ACTUALIZAR");
            }
        }


    }//GEN-LAST:event_btneditarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        titulo.setText("Nuevo registro");
        btnGuardar.setBackground(new Color(26, 187, 156));
        btnGuardar.setText("GUARDAR");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        String nombre = this.nombre.getText();
        String codigo = this.codigo.getText();
        String municipionombre = this.combomunicipios.getSelectedItem().toString();
        municipio = buscarID(municipionombre);
        comunidades = new Comunidades();
        if (!this.nombre.getText().isEmpty() && !this.codigo.getText().isEmpty() && this.combomunicipios.getSelectedIndex() != 0) {
            /*seteando los datos para mandarlos a la base de datos*/
            comunidades.setNombre(nombre);
            comunidades.setCodigo(codigo);
            comunidades.setIdmunicipio(municipio.getIdmunicipio());

            comunidades1 = buscarcomunidad(nombre);
            /*SERAN EDITAR O GUARDAR SEGUN EL TEXTO DEL BOTON QUE MANIPULA LOS DATOS PARA ENVIARLOS A LA DB*/
            if (this.btnGuardar.getText().equals("GUARDAR")) {
                if (comunidades1 == null) {
                    comuni.insertar(comunidades);
                    ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                    er.titulo.setText("REGSITRO GUARDADO");
                    er.msj.setText("REGSITRO INGRESADO");
                    er.msj1.setText("SATISFACTORIAMENTE");
                    er.setVisible(true);
                    llenarTabla();
                    limpiar();
                } else {
                    ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                    er.titulo.setText("ERROR");
                    er.msj.setText("LA COMUNIDAD YA HA SIDO");
                    er.msj1.setText("REGISTRADA");
                    er.setVisible(true);
                }
            } else if (this.btnGuardar.getText().equals("ACTUALIZAR")) {
                comunidades.setIdcomunidades(Integer.parseInt(this.id.getText()));
                comuni.editar(comunidades);
                ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                er.titulo.setText("REGSITRO MODIFICADO");
                er.msj.setText("REGSITRO ACTUALIZADO");
                er.msj1.setText("SATISFACTORIAMENTE");
                er.setVisible(true);
                titulo.setText("Nuevo registro");
                btnGuardar.setBackground(new Color(26, 187, 156));
                btnGuardar.setText("GUARDAR");
                llenarTabla();
                limpiar();
            }
        } else {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("CAMPOS VACÍOS");
            er.msj.setText("POR FAVOR LLENE LOS CAMPOS");
            er.msj1.setText("SOLICITADOS");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void panel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MouseDragged

    }//GEN-LAST:event_panel1MouseDragged

    private void panel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel1MousePressed

    }//GEN-LAST:event_panel1MousePressed

    private void nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreKeyReleased
        // TODO add your handling code here:
        if (this.nombre.getText().equals("")) {
            this.codigo.setText("");
        } else {
            String codigo = Recursividad.primeraultima(this.nombre.getText().trim());
            this.codigo.setText(codigo.toUpperCase() + String.valueOf(Recursividad.cuatrodigitos()));
        }
    }//GEN-LAST:event_nombreKeyReleased

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        String bsc = this.buscar.getText();
        comunidades = new Comunidades(bsc);
        Nodo dato = comuni.ldc.buscar(comunidades);
        if (dato != null) {
            JOptionPane.showMessageDialog(null, "DATOS DE LA COMUNIDAD\n\n"
                    + "Código: " + ((Comunidades) dato.getDato()).getCodigo()
                    + "\nNombre del Municipio: " + ((Comunidades) dato.getDato()).getNombre()
                    + "\nMunicipio: " + ((Comunidades) dato.getDato()).getMunicipios().getNombre(),
                    "Busqueda Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.buscar.setText("");
        } else {
            this.buscar.setText("");
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("ERROR DE BÚSQUEDA");
            er.msj.setText("EL REGSITRO NO EXISTE");
            er.msj1.setText("");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    /*Llenando la tabla de datos*/
    public void llenarTabla() {
        comuni = new dao_comunidades();
        eliminarFilas();
        ocultar_columnas();
        int registros = 0;
        String[] m = new String[4];
        for (Comunidades d : comuni.llenarlista(comuni.consultacomunidades())) {
            m[0] = String.valueOf(d.getIdmunicipio());
            m[1] = d.getCodigo();
            m[2] = d.getNombre();
            m[3] = d.getMunicipios().getNombre();
            modelo.addRow(m);
            registros += 1;
        }
        this.totregistros.setText(String.valueOf(registros));
    }

    /*Metodo de eliminacion de las filas para que no se dupliquen los datos al mostrarlos al registrar uno nuevo*/
    public void eliminarFilas() {
        try {
            int filas = modelo.getRowCount();
            for (int i = 0; filas > i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede limpiar la tabla", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    /*metodo limpiar los campos*/
    public void limpiar() {
        this.nombre.setText("");
        this.codigo.setText("");
        this.combomunicipios.setSelectedIndex(0);
    }

    /*metodo para buscar el id del combo para insertar y tambien modificar*/
    public Municipio buscarID(String nombre) {

        for (Municipio x : muni.llenarlista(muni.consultamunicipios())) {
            if (x.getNombre().equals(nombre)) {
                return x;
            }
        }
        return null;
    }

    /*Metodo para llenar el combo con los municipios registrados en la base de datos*/
    public void llenarcombomunicipios() {
        for (Municipio x : muni.llenarlista(muni.consultamunicipios())) {
            combomunicipios.addItem(x.getNombre());
        }
    }

    /*metodo para buscar comunidades ya ingresadas*/
    public Comunidades buscarcomunidad(String g) {
        for (Comunidades c : comuni.llenarlista(comuni.consultacomunidades())) {
            if (c.getNombre().equals(g)) {
                return c;
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnCancelar;
    public principal.MaterialButton btnGuardar;
    private rsbuttom.RSButtonMetro btnbuscar;
    private principal.MaterialButton btncerrar;
    private principal.MaterialButton btneditar;
    private principal.MaterialButton btneliminar;
    public static app.bolivia.swing.JCTextField buscar;
    public app.bolivia.swing.JCTextField codigo;
    private javax.swing.JComboBox<String> combomunicipios;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public app.bolivia.swing.JCTextField nombre;
    private org.edisoncor.gui.panel.Panel panel1;
    public static javax.swing.JTable tablaComunidades;
    public javax.swing.JLabel titulo;
    public static javax.swing.JLabel totregistros;
    // End of variables declaration//GEN-END:variables
}
