/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package donantes;

import Alertas.AlertadeEliminacion;
import Alertas.ErrordeProcesos;
import Alertas.ProcesoExitoso;
import EstilodelasTablas.EstiloTablaHeader;
import EstilodelasTablas.EstiloTablaRenderer;
import EstilodelasTablas.MyScrollbarUI;
import EstilodelasTablas.MyScrollbarVistas;
import ListasSimples.Nodo;
import Validaciones.Validaciones;
import donaciones.Donaciones;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sony
 */
public class registrodatosdedonantes extends javax.swing.JInternalFrame {

    DefaultTableModel model;
    dao_donantes donantes = new dao_donantes();
    Donantes dn;
    Donantes dn1 = new Donantes();
    /*variables para la eliminacion de donantes*/
    Validaciones validaciones = new Validaciones();
    Donaciones donaciones = new Donaciones();

    /**
     * Creates new form NewJInternalFrame
     */
    public registrodatosdedonantes() {
        initComponents();
        this.tablaDonantes.getTableHeader().setDefaultRenderer(new EstiloTablaHeader());
        this.tablaDonantes.setDefaultRenderer(Object.class, new EstiloTablaRenderer());
        this.tablaDonantes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.getVerticalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane1.getHorizontalScrollBar().setUI(new MyScrollbarUI());
        jScrollPane2.getViewport().setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.getVerticalScrollBar().setUI(new MyScrollbarVistas());
        jScrollPane2.getHorizontalScrollBar().setUI(new MyScrollbarVistas());
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.id.setVisible(false);
        this.pais.setVisible(false);
        titulo1.setText("Nuevo registro");
        jLabel10.setVisible(false);
        model = (DefaultTableModel) tablaDonantes.getModel();
        llenarTabla();
    }

    void ocultar_columnas() {
        this.tablaDonantes.getColumnModel().getColumn(0).setMaxWidth(0);
        this.tablaDonantes.getColumnModel().getColumn(0).setMinWidth(0);
        this.tablaDonantes.getColumnModel().getColumn(0).setPreferredWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        materialButtonCircle1 = new principal.MaterialButtonCircle();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDonantes = new javax.swing.JTable();
        btneditar = new principal.MaterialButton();
        btneliminar = new principal.MaterialButton();
        buscar = new app.bolivia.swing.JCTextField();
        jLabel2 = new javax.swing.JLabel();
        totregistros = new javax.swing.JLabel();
        btnbuscar = new rsbuttom.RSButtonMetro();
        jPanel4 = new javax.swing.JPanel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        jPanel5 = new javax.swing.JPanel();
        titulo1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nombre = new app.bolivia.swing.JCTextField();
        empresa = new app.bolivia.swing.JCTextField();
        jLabel8 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        id = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        email = new app.bolivia.swing.JCTextField();
        direccion = new app.bolivia.swing.JCTextField();
        jLabel4 = new javax.swing.JLabel();
        postal = new app.bolivia.swing.JCTextField();
        jLabel5 = new javax.swing.JLabel();
        ciudad = new app.bolivia.swing.JCTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pais = new app.bolivia.swing.JCTextField();
        telefono = new javax.swing.JFormattedTextField();
        btnCancelar = new principal.MaterialButton();
        btnGuardar = new principal.MaterialButton();
        jLabel1 = new javax.swing.JLabel();
        btncerrar = new principal.MaterialButton();

        materialButtonCircle1.setText("materialButtonCircle1");

        setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder1 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder1.setShowLeftShadow(true);
        dropShadowBorder1.setShowTopShadow(true);
        setBorder(dropShadowBorder1);

        jPanel1.setBackground(new java.awt.Color(248, 248, 248));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        tablaDonantes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tablaDonantes.setForeground(new java.awt.Color(255, 255, 255));
        tablaDonantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "EMPRESA", "EMAIL", "DIRECCIÓN", "CÓDIGO POSTAL", "CIUDAD", "TELÉFONO", "TIPO", "PAÍS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDonantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tablaDonantes.setDoubleBuffered(true);
        tablaDonantes.setRowHeight(20);
        tablaDonantes.setSelectionBackground(new java.awt.Color(0, 153, 255));
        tablaDonantes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaDonantes);
        if (tablaDonantes.getColumnModel().getColumnCount() > 0) {
            tablaDonantes.getColumnModel().getColumn(0).setMinWidth(70);
            tablaDonantes.getColumnModel().getColumn(0).setMaxWidth(70);
        }

        btneditar.setBackground(new java.awt.Color(51, 85, 193));
        btneditar.setForeground(new java.awt.Color(255, 255, 255));
        btneditar.setText("EDITAR");
        btneditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneditar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btneditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditarActionPerformed(evt);
            }
        });

        btneliminar.setBackground(new java.awt.Color(243, 156, 17));
        btneliminar.setForeground(new java.awt.Color(255, 255, 255));
        btneliminar.setText("ELIMINAR");
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        buscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(26, 187, 156)));
        buscar.setForeground(new java.awt.Color(26, 187, 156));
        buscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscar.setPlaceholder("BUSCAR DONANTE");
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(42, 63, 84));
        jLabel2.setText("Total de Registros");

        totregistros.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        totregistros.setForeground(new java.awt.Color(42, 63, 84));
        totregistros.setText("0000");

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDonantes/icons8_Search_30px.png"))); // NOI18N
        btnbuscar.setColorHover(new java.awt.Color(229, 226, 229));
        btnbuscar.setColorNormal(new java.awt.Color(255, 255, 255));
        btnbuscar.setColorPressed(new java.awt.Color(248, 246, 246));
        btnbuscar.setColorTextHover(new java.awt.Color(248, 246, 246));
        btnbuscar.setDefaultCapable(false);
        btnbuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnbuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(26, 187, 156));

        panel2.setBackground(new java.awt.Color(255, 255, 255));
        panel2.setForeground(new java.awt.Color(255, 255, 255));
        panel2.setColorPrimario(new java.awt.Color(255, 255, 255));
        panel2.setColorSecundario(new java.awt.Color(255, 255, 255));
        panel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel2MouseDragged(evt);
            }
        });
        panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel2MousePressed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(26, 187, 156));

        titulo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo1.setForeground(new java.awt.Color(255, 255, 255));
        titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo1.setText("TITULO");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        org.jdesktop.swingx.border.DropShadowBorder dropShadowBorder2 = new org.jdesktop.swingx.border.DropShadowBorder();
        dropShadowBorder2.setShowLeftShadow(true);
        dropShadowBorder2.setShowTopShadow(true);
        jPanel6.setBorder(dropShadowBorder2);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(26, 187, 156));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Dirección:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 187, 156));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Nombre:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 187, 156));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Empresa:");

        tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione:", "Nacional", "Extranjero" }));
        tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tipoItemStateChanged(evt);
            }
        });

        id.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("id");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(26, 187, 156));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("E-mail:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(26, 187, 156));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("C. Postal:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 187, 156));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ciudad:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 187, 156));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Teléfono:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(26, 187, 156));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tipo:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(26, 187, 156));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("País:");

        try {
            telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(postal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(telefono)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btnCancelar.setBackground(new java.awt.Color(243, 156, 17));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("");
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(26, 187, 156));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("GUARDAR");
        btnGuardar.setToolTipText("");
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setFont(new java.awt.Font("Roboto Medium", 1, 14)); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 452, Short.MAX_VALUE)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totregistros)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btneditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btneliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totregistros))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel7);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(42, 63, 84));
        jLabel1.setText("Registro de Donantes");

        btncerrar.setBackground(new java.awt.Color(42, 63, 84));
        btncerrar.setForeground(new java.awt.Color(255, 255, 255));
        btncerrar.setText("X");
        btncerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncerrar.setFont(new java.awt.Font("Calibri Light", 0, 20)); // NOI18N
        btncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 467, Short.MAX_VALUE)
                .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1194, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(551, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        if (this.tablaDonantes.getRowCount() < 1) {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("NO HAY REGISTROS");
            er.msj1.setText("");
            er.setVisible(true);
        } else {
            if (this.tablaDonantes.getSelectedRowCount() < 1) {
                ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {
                int fila = this.tablaDonantes.getSelectedRow();
                int iddonante = Integer.parseInt(this.tablaDonantes.getValueAt(fila, 0).toString());
                donaciones = validaciones.buscardonaciones(iddonante, 0);
                if (donaciones == null) {
                    AlertadeEliminacion wa = new AlertadeEliminacion(new JFrame(), true);
                    wa.titulo.setText("¿ESTAS SEGURO?");
                    wa.msj.setText("SE BORRARA PERMANENTEMENTE");
                    wa.msj1.setText("EL REGISTRO SELECCIONADO");
                    wa.setVisible(true);
                    if (AlertadeEliminacion.salir == true) {
                        wa.nombre.setText(this.tablaDonantes.getValueAt(fila, 1).toString());/*agarrando el dato del nombre de la tabla para proceder 
                    a la busqueda para eliminarlo con la lista circular doble*/
                        dn = new Donantes(wa.nombre.getText());
                        Nodo dato = donantes.ls.eliminar(dn);/*salvando el registro eliminado de la lista*/
                        if (dato != null) {
                            donantes.eliminar((Donantes) dato.getA());/*eliminando el registro de la base de datos*/
                            llenarTabla();
                            ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                            er.titulo.setText("");
                            er.msj.setText("REGSITRO ELIMINADO");
                            er.msj1.setText("SATISFACTORIAMENTE");
                            er.setVisible(true);
                        } else {
                            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                            er.titulo.setText("OOPS...");
                            er.msj.setText("EL REGISTRO NO SE");
                            er.msj1.setText("PUDO ELIMINAR");
                            er.setVisible(true);
                        }
                    }
                } else {
                    ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                    er.titulo.setText("OOPS...");
                    er.msj.setText("ESTE REGISTRO NO SE");
                    er.msj1.setText("PUEDE ELIMINAR");
                    er.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
//        dep.consultadepartamentos();
//        llenarTabla();
    }//GEN-LAST:event_buscarKeyReleased

    private void btneditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditarActionPerformed
        // TODO add your handling code here:
        if (this.tablaDonantes.getRowCount() < 1) {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("OOPS...");
            er.msj.setText("NO HAY REGISTROS");
            er.msj1.setText("");
            er.setVisible(true);
        } else {
            if (this.tablaDonantes.getSelectedRowCount() < 1) {
                ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                er.titulo.setText("OOPS...");
                er.msj.setText("SELECCIONA UN");
                er.msj1.setText("REGISTRO");
                er.setVisible(true);
            } else {

                int fila = this.tablaDonantes.getSelectedRow();
                id.setText(this.tablaDonantes.getValueAt(fila, 0).toString());
                nombre.setText(this.tablaDonantes.getValueAt(fila, 1).toString());
                empresa.setText(this.tablaDonantes.getValueAt(fila, 2).toString());
                email.setText(this.tablaDonantes.getValueAt(fila, 3).toString());
                direccion.setText(this.tablaDonantes.getValueAt(fila, 4).toString());
                postal.setText(this.tablaDonantes.getValueAt(fila, 5).toString());
                ciudad.setText(this.tablaDonantes.getValueAt(fila, 6).toString());
                telefono.setText(this.tablaDonantes.getValueAt(fila, 7).toString());
                tipo.setSelectedItem(this.tablaDonantes.getValueAt(fila, 8));
                pais.setText(this.tablaDonantes.getValueAt(fila, 9).toString());
                titulo1.setText("Editar registro");
                btnGuardar.setBackground(new Color(51, 85, 193));
                btnGuardar.setText("ACTUALIZAR");
            }
        }


    }//GEN-LAST:event_btneditarActionPerformed

    private void btncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncerrarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
        dn = new Donantes(buscar.getText());
        Nodo don = donantes.ls.buscar(dn);
        if (don != null) {
            JOptionPane.showMessageDialog(null, "\t\tINFORMACIÓN DEL DONANTE\n\nNombre: " + ((Donantes) don.getA()).getNombre() + "\n "
                    + "Empresa: " + ((Donantes) don.getA()).getEmpresa() + "\n"
                    + "E-mail: " + ((Donantes) don.getA()).getEmail() + "\n"
                    + "Dirección: " + ((Donantes) don.getA()).getDireccion() + "\n"
                    + "Código Postal: " + ((Donantes) don.getA()).getCodigopostal() + "\n"
                    + "Ciudad: " + ((Donantes) don.getA()).getCiudad() + "\n"
                    + "Teléfono: " + ((Donantes) don.getA()).getTelefono() + "\n"
                    + "Tipo: " + ((Donantes) don.getA()).getTipo() + "\n"
                    + "País: " + ((Donantes) don.getA()).getPais() + "\n",
                    "Busqueda Exitosa", JOptionPane.INFORMATION_MESSAGE);
            this.buscar.setText("");
        } else {
            this.buscar.setText("");
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("ERROR DE BÚSQUEDA");
            er.msj.setText("EL REGSITRO NO EXISTE");
            er.msj1.setText("");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tipoItemStateChanged
        // TODO add your handling code here:
        if (this.tipo.getSelectedItem().equals("Seleccione:")) {
            jLabel10.setVisible(false);
            this.pais.setVisible(false);
        } else if (this.tipo.getSelectedItem().equals("Extranjero")) {
            jLabel10.setVisible(true);
            this.pais.setVisible(true);
        } else if (this.tipo.getSelectedItem().equals("Nacional")) {
            jLabel10.setVisible(false);
            this.pais.setVisible(false);
        }
    }//GEN-LAST:event_tipoItemStateChanged

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        limpiar();
        titulo1.setText("Nuevo registro");
        btnGuardar.setBackground(new Color(26, 187, 156));
        btnGuardar.setText("GUARDAR");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        dn = new Donantes();
        String nombre = this.nombre.getText();
        String empresa = this.empresa.getText();
        String email = this.email.getText();
        String direccion = this.direccion.getText();
        String postal = this.postal.getText();
        String ciudad = this.ciudad.getText();
        String telefono = this.telefono.getText();
        String tipo = this.tipo.getSelectedItem().toString();
        String pais = this.pais.getText();

        if (!this.nombre.getText().isEmpty() && !this.empresa.getText().isEmpty() && !this.email.getText().isEmpty()
                && !this.direccion.getText().isEmpty() && !this.postal.getText().isEmpty() && !this.ciudad.getText().isEmpty()
                && !this.telefono.getText().isEmpty() && this.tipo.getSelectedIndex() != 0) {
            if (this.tipo.getSelectedItem().equals("Extranjero")) {
                dn.setNombre(nombre);
                dn.setEmpresa(empresa);
                dn.setEmail(email);
                dn.setDireccion(direccion);
                dn.setCodigopostal(postal);
                dn.setCiudad(ciudad);
                dn.setTelefono(telefono);
                dn.setTipo(tipo);
                dn.setPais(pais);
            } else if (this.tipo.getSelectedItem().equals("Nacional")) {
                dn.setNombre(nombre);
                dn.setEmpresa(empresa);
                dn.setEmail(email);
                dn.setDireccion(direccion);
                dn.setCodigopostal(postal);
                dn.setCiudad(ciudad);
                dn.setTelefono(telefono);
                dn.setTipo(tipo);
                dn.setPais("");
            }
            dn1 = buscarempresa(empresa);
            if (this.btnGuardar.getText().equals("GUARDAR")) {
                if (dn1 == null) {
                    donantes.insertar(dn);
                    ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                    er.titulo.setText("REGSITRO GUARDADO");
                    er.msj.setText("REGSITRO INGRESADO");
                    er.msj1.setText("SATISFACTORIAMENTE");
                    er.setVisible(true);
                    llenarTabla();
                    limpiar();
                } else {
                    ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
                    er.titulo.setText("ERROR");
                    er.msj.setText("LA EMPRESA YA HA SIDO INGRESADA");
                    er.msj1.setText("");
                    er.setVisible(true);
                }
            } else if (this.btnGuardar.getText().equals("ACTUALIZAR")) {
                dn.setIddonantes(Integer.parseInt(this.id.getText()));
                donantes.editar(dn);
                ProcesoExitoso er = new ProcesoExitoso(new JFrame(), true);
                er.titulo.setText("REGSITRO MODIFICADO");
                er.msj.setText("REGSITRO ACTUALIZADO");
                er.msj1.setText("SATISFACTORIAMENTE");
                er.setVisible(true);
                titulo1.setText("Nuevo registro");
                btnGuardar.setBackground(new Color(26, 187, 156));
                btnGuardar.setText("GUARDAR");
                llenarTabla();
                limpiar();
            }
        } else {
            ErrordeProcesos er = new ErrordeProcesos(new JFrame(), true);
            er.titulo.setText("CAMPOS VACÍOS");
            er.msj.setText("POR FAVOR LLENE LOS CAMPOS");
            er.msj1.setText("SOLICITADOS");
            er.setVisible(true);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void panel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MouseDragged
//        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_panel2MouseDragged

    private void panel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel2MousePressed
//        x = evt.getX();
//        y = evt.getY();
    }//GEN-LAST:event_panel2MousePressed

    /*Llenando la tabla de datos*/
    public void llenarTabla() {
        donantes = new dao_donantes();
        eliminarFilas();
        ocultar_columnas();
        int registros = 0;
        String[] m = new String[10];
        for (Donantes d : donantes.llenarlista(donantes.consultadonantes())) {
            m[0] = String.valueOf(d.getIddonantes());
            m[1] = d.getNombre();
            m[2] = d.getEmpresa();
            m[3] = d.getEmail();
            m[4] = d.getDireccion();
            m[5] = d.getCodigopostal();
            m[6] = d.getCiudad();
            m[7] = d.getTelefono();
            m[8] = d.getTipo();
            m[9] = d.getPais();
            model.addRow(m);
            registros += 1;
        }
        this.totregistros.setText(String.valueOf(registros));
    }

    /*Metodo de eliminacion de las filas para que no se dupliquen los datos al mostrarlos al registrar uno nuevo*/
    public void eliminarFilas() {
        try {
            int filas = model.getRowCount();
            for (int i = 0; filas > i; i++) {
                model.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "No se puede limpiar la tabla", "", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public Donantes buscarempresa(String g) {
        for (Donantes d : donantes.llenarlista(donantes.consultadonantes())) {
            if (d.getEmpresa().equals(g)) {
                return d;
            }
        }
        return null;
    }

    /*metodo limpiar los campos*/
    public void limpiar() {
        this.nombre.setText("");
        this.empresa.setText("");
        this.email.setText("");
        this.direccion.setText("");
        this.postal.setText("");
        this.ciudad.setText("");
        this.telefono.setText("");
        this.pais.setText("");
        this.tipo.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private principal.MaterialButton btnCancelar;
    public principal.MaterialButton btnGuardar;
    private rsbuttom.RSButtonMetro btnbuscar;
    private principal.MaterialButton btncerrar;
    private principal.MaterialButton btneditar;
    private principal.MaterialButton btneliminar;
    public static app.bolivia.swing.JCTextField buscar;
    public app.bolivia.swing.JCTextField ciudad;
    public app.bolivia.swing.JCTextField direccion;
    public app.bolivia.swing.JCTextField email;
    public app.bolivia.swing.JCTextField empresa;
    public javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private principal.MaterialButtonCircle materialButtonCircle1;
    public app.bolivia.swing.JCTextField nombre;
    public app.bolivia.swing.JCTextField pais;
    private org.edisoncor.gui.panel.Panel panel2;
    public app.bolivia.swing.JCTextField postal;
    public static javax.swing.JTable tablaDonantes;
    private javax.swing.JFormattedTextField telefono;
    public javax.swing.JComboBox<String> tipo;
    public javax.swing.JLabel titulo1;
    public static javax.swing.JLabel totregistros;
    // End of variables declaration//GEN-END:variables
}
